/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteRouteImport } from './routes/login/route';
import { Route as ContactRouteRouteImport } from './routes/contact/route';
import { Route as IndexRouteRouteImport } from './routes/index/route';
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements/index';
import { Route as ResearchProjectsIndexRouteImport } from './routes/research_/projects/index';
import { Route as EventsRoundTablesIndexRouteImport } from './routes/events_/round-tables/index';
import { Route as EventsPhdThesesIndexRouteImport } from './routes/events_/phd-theses/index';
import { Route as AboutPartnersIndexRouteImport } from './routes/about_/partners/index';
import { Route as AboutMembersIndexRouteImport } from './routes/about_/members/index';
import { Route as AboutHistoryIndexRouteImport } from './routes/about_/history/index';
import { Route as AboutDescriptionAndObjectivesIndexRouteImport } from './routes/about_/description-and-objectives/index';
import { Route as EventsRoundTablesArchiveRouteImport } from './routes/events_/round-tables/archive';
import { Route as EventsPhdThesesArchiveRouteImport } from './routes/events_/phd-theses/archive';
import { Route as ResearchPublicationsTranslationsIndexRouteImport } from './routes/research_/publications_/translations/index';
import { Route as ResearchPublicationsMembersPublicationsIndexRouteImport } from './routes/research_/publications_/members-publications/index';
import { Route as ResearchPublicationsLingvisticConferencesIndexRouteImport } from './routes/research_/publications_/lingvistic-conferences/index';
import { Route as EventsConferencesLingvisticFrancophonesIndexRouteImport } from './routes/events_/conferences_/lingvistic-francophones/index';
import { Route as ResearchPublicationsDialogueFrancophonesVolumesIndexRouteImport } from './routes/research_/publications_/dialogue-francophones_/volumes/index';
import { Route as ResearchPublicationsDialogueFrancophonesIndexingIndexRouteImport } from './routes/research_/publications_/dialogue-francophones_/indexing/index';
import { Route as ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRouteImport } from './routes/research_/publications_/dialogue-francophones_/editorial-policy/index';
import { Route as ResearchPublicationsDialogueFrancophonesCommitteesIndexRouteImport } from './routes/research_/publications_/dialogue-francophones_/committees/index';
import { Route as ResearchPublicationsDialogueFrancophonesAboutIndexRouteImport } from './routes/research_/publications_/dialogue-francophones_/about/index';
import { Route as ResearchPublicationsAgapesFrancophonesVolumesIndexRouteImport } from './routes/research_/publications_/agapes-francophones_/volumes/index';
import { Route as ResearchPublicationsAgapesFrancophonesIndexingIndexRouteImport } from './routes/research_/publications_/agapes-francophones_/indexing/index';
import { Route as ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRouteImport } from './routes/research_/publications_/agapes-francophones_/editorial-policy/index';
import { Route as ResearchPublicationsAgapesFrancophonesCommitteesIndexRouteImport } from './routes/research_/publications_/agapes-francophones_/committees/index';
import { Route as ResearchPublicationsAgapesFrancophonesAboutIndexRouteImport } from './routes/research_/publications_/agapes-francophones_/about/index';
import { Route as EventsConferencesFrancophonesStudiesPreviousEditionsIndexRouteImport } from './routes/events_/conferences_/francophones-studies_/previous-editions_/index';
import { Route as EventsConferencesCieftPreviousEditionsIndexRouteImport } from './routes/events_/conferences_/cieft_/previous-editions_/index';
import { Route as ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRouteImport } from './routes/research_/publications_/dialogue-francophones_/volumes/$volumeId';
import { Route as ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRouteImport } from './routes/research_/publications_/dialogue-francophones_/registration/registration';
import { Route as ResearchPublicationsDialogueFrancophonesCallsCallIdRouteImport } from './routes/research_/publications_/dialogue-francophones_/calls_/$callId';
import { Route as EventsConferencesFrancophonesStudiesPreviousEditionsYearRouteImport } from './routes/events_/conferences_/francophones-studies_/previous-editions_/$year';
import { Route as EventsConferencesFrancophonesStudiesCurrentYearRegistrationRouteImport } from './routes/events_/conferences_/francophones-studies_/current-year_/registration';
import { Route as EventsConferencesCieftPreviousEditionsYearRouteImport } from './routes/events_/conferences_/cieft_/previous-editions_/$year';
import { Route as EventsConferencesCieftCurrentYearRegistrationRouteImport } from './routes/events_/conferences_/cieft_/current-year_/registration';
import { Route as ResearchPublicationsDialogueFrancophonesCallsPastIndexRouteImport } from './routes/research_/publications_/dialogue-francophones_/calls_/past/index';
import { Route as ResearchPublicationsDialogueFrancophonesCallsFutureIndexRouteImport } from './routes/research_/publications_/dialogue-francophones_/calls_/future/index';
import { Route as ResearchPublicationsAgapesFrancophonesCallsPastIndexRouteImport } from './routes/research_/publications_/agapes-francophones_/calls_/past/index';
import { Route as ResearchPublicationsAgapesFrancophonesCallsFutureIndexRouteImport } from './routes/research_/publications_/agapes-francophones_/calls_/future/index';
import { Route as EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRouteImport } from './routes/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners/index';
import { Route as EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRouteImport } from './routes/events_/conferences_/francophones-studies_/current-year_/events/index';
import { Route as EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRouteImport } from './routes/events_/conferences_/francophones-studies_/current-year_/calls/index';
import { Route as EventsConferencesCieftCurrentYearScientificCommitteeIndexRouteImport } from './routes/events_/conferences_/cieft_/current-year_/scientific-committee/index';
import { Route as EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRouteImport } from './routes/events_/conferences_/cieft_/current-year_/organizers-and-partners/index';
import { Route as EventsConferencesCieftCurrentYearInfoIndexRouteImport } from './routes/events_/conferences_/cieft_/current-year_/info/index';
import { Route as EventsConferencesCieftCurrentYearEventsIndexRouteImport } from './routes/events_/conferences_/cieft_/current-year_/events/index';
import { Route as EventsConferencesCieftCurrentYearCallsIndexRouteImport } from './routes/events_/conferences_/cieft_/current-year_/calls/index';
import { Route as EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRouteImport } from './routes/events_/conferences_/francophones-studies_/current-year_/info/info';
import { Route as EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRouteImport } from './routes/events_/conferences_/francophones-studies_/current-year_/events/archive';
import { Route as EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRouteImport } from './routes/events_/conferences_/francophones-studies_/current-year_/committee/scientific-committee';
import { Route as EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRouteImport } from './routes/events_/conferences_/francophones-studies_/current-year_/calls/archive';
import { Route as EventsConferencesCieftCurrentYearInfoArchiveRouteImport } from './routes/events_/conferences_/cieft_/current-year_/info/archive';
import { Route as EventsConferencesCieftCurrentYearEventsArchiveRouteImport } from './routes/events_/conferences_/cieft_/current-year_/events/archive';
import { Route as EventsConferencesCieftCurrentYearCallsArchiveRouteImport } from './routes/events_/conferences_/cieft_/current-year_/calls/archive';

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const ContactRouteRoute = ContactRouteRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any);
const ResearchProjectsIndexRoute = ResearchProjectsIndexRouteImport.update({
  id: '/research_/projects/',
  path: '/research/projects/',
  getParentRoute: () => rootRouteImport,
} as any);
const EventsRoundTablesIndexRoute = EventsRoundTablesIndexRouteImport.update({
  id: '/events_/round-tables/',
  path: '/events/round-tables/',
  getParentRoute: () => rootRouteImport,
} as any);
const EventsPhdThesesIndexRoute = EventsPhdThesesIndexRouteImport.update({
  id: '/events_/phd-theses/',
  path: '/events/phd-theses/',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutPartnersIndexRoute = AboutPartnersIndexRouteImport.update({
  id: '/about_/partners/',
  path: '/about/partners/',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutMembersIndexRoute = AboutMembersIndexRouteImport.update({
  id: '/about_/members/',
  path: '/about/members/',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutHistoryIndexRoute = AboutHistoryIndexRouteImport.update({
  id: '/about_/history/',
  path: '/about/history/',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutDescriptionAndObjectivesIndexRoute =
  AboutDescriptionAndObjectivesIndexRouteImport.update({
    id: '/about_/description-and-objectives/',
    path: '/about/description-and-objectives/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsRoundTablesArchiveRoute =
  EventsRoundTablesArchiveRouteImport.update({
    id: '/events_/round-tables/archive',
    path: '/events/round-tables/archive',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsPhdThesesArchiveRoute = EventsPhdThesesArchiveRouteImport.update({
  id: '/events_/phd-theses/archive',
  path: '/events/phd-theses/archive',
  getParentRoute: () => rootRouteImport,
} as any);
const ResearchPublicationsTranslationsIndexRoute =
  ResearchPublicationsTranslationsIndexRouteImport.update({
    id: '/research_/publications_/translations/',
    path: '/research/publications/translations/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsMembersPublicationsIndexRoute =
  ResearchPublicationsMembersPublicationsIndexRouteImport.update({
    id: '/research_/publications_/members-publications/',
    path: '/research/publications/members-publications/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsLingvisticConferencesIndexRoute =
  ResearchPublicationsLingvisticConferencesIndexRouteImport.update({
    id: '/research_/publications_/lingvistic-conferences/',
    path: '/research/publications/lingvistic-conferences/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesLingvisticFrancophonesIndexRoute =
  EventsConferencesLingvisticFrancophonesIndexRouteImport.update({
    id: '/events_/conferences_/lingvistic-francophones/',
    path: '/events/conferences/lingvistic-francophones/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsDialogueFrancophonesVolumesIndexRoute =
  ResearchPublicationsDialogueFrancophonesVolumesIndexRouteImport.update({
    id: '/research_/publications_/dialogue-francophones_/volumes/',
    path: '/research/publications/dialogue-francophones/volumes/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsDialogueFrancophonesIndexingIndexRoute =
  ResearchPublicationsDialogueFrancophonesIndexingIndexRouteImport.update({
    id: '/research_/publications_/dialogue-francophones_/indexing/',
    path: '/research/publications/dialogue-francophones/indexing/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute =
  ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRouteImport.update(
    {
      id: '/research_/publications_/dialogue-francophones_/editorial-policy/',
      path: '/research/publications/dialogue-francophones/editorial-policy/',
      getParentRoute: () => rootRouteImport,
    } as any
  );
const ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute =
  ResearchPublicationsDialogueFrancophonesCommitteesIndexRouteImport.update({
    id: '/research_/publications_/dialogue-francophones_/committees/',
    path: '/research/publications/dialogue-francophones/committees/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsDialogueFrancophonesAboutIndexRoute =
  ResearchPublicationsDialogueFrancophonesAboutIndexRouteImport.update({
    id: '/research_/publications_/dialogue-francophones_/about/',
    path: '/research/publications/dialogue-francophones/about/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsAgapesFrancophonesVolumesIndexRoute =
  ResearchPublicationsAgapesFrancophonesVolumesIndexRouteImport.update({
    id: '/research_/publications_/agapes-francophones_/volumes/',
    path: '/research/publications/agapes-francophones/volumes/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsAgapesFrancophonesIndexingIndexRoute =
  ResearchPublicationsAgapesFrancophonesIndexingIndexRouteImport.update({
    id: '/research_/publications_/agapes-francophones_/indexing/',
    path: '/research/publications/agapes-francophones/indexing/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute =
  ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRouteImport.update({
    id: '/research_/publications_/agapes-francophones_/editorial-policy/',
    path: '/research/publications/agapes-francophones/editorial-policy/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute =
  ResearchPublicationsAgapesFrancophonesCommitteesIndexRouteImport.update({
    id: '/research_/publications_/agapes-francophones_/committees/',
    path: '/research/publications/agapes-francophones/committees/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsAgapesFrancophonesAboutIndexRoute =
  ResearchPublicationsAgapesFrancophonesAboutIndexRouteImport.update({
    id: '/research_/publications_/agapes-francophones_/about/',
    path: '/research/publications/agapes-francophones/about/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute =
  EventsConferencesFrancophonesStudiesPreviousEditionsIndexRouteImport.update({
    id: '/events_/conferences_/francophones-studies_/previous-editions_/',
    path: '/events/conferences/francophones-studies/previous-editions/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesCieftPreviousEditionsIndexRoute =
  EventsConferencesCieftPreviousEditionsIndexRouteImport.update({
    id: '/events_/conferences_/cieft_/previous-editions_/',
    path: '/events/conferences/cieft/previous-editions/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute =
  ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRouteImport.update({
    id: '/research_/publications_/dialogue-francophones_/volumes/$volumeId',
    path: '/research/publications/dialogue-francophones/volumes/$volumeId',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute =
  ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRouteImport.update(
    {
      id: '/research_/publications_/dialogue-francophones_/registration/registration',
      path: '/research/publications/dialogue-francophones/registration/registration',
      getParentRoute: () => rootRouteImport,
    } as any
  );
const ResearchPublicationsDialogueFrancophonesCallsCallIdRoute =
  ResearchPublicationsDialogueFrancophonesCallsCallIdRouteImport.update({
    id: '/research_/publications_/dialogue-francophones_/calls_/$callId',
    path: '/research/publications/dialogue-francophones/calls/$callId',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute =
  EventsConferencesFrancophonesStudiesPreviousEditionsYearRouteImport.update({
    id: '/events_/conferences_/francophones-studies_/previous-editions_/$year',
    path: '/events/conferences/francophones-studies/previous-editions/$year',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute =
  EventsConferencesFrancophonesStudiesCurrentYearRegistrationRouteImport.update(
    {
      id: '/events_/conferences_/francophones-studies_/current-year_/registration',
      path: '/events/conferences/francophones-studies/current-year/registration',
      getParentRoute: () => rootRouteImport,
    } as any
  );
const EventsConferencesCieftPreviousEditionsYearRoute =
  EventsConferencesCieftPreviousEditionsYearRouteImport.update({
    id: '/events_/conferences_/cieft_/previous-editions_/$year',
    path: '/events/conferences/cieft/previous-editions/$year',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesCieftCurrentYearRegistrationRoute =
  EventsConferencesCieftCurrentYearRegistrationRouteImport.update({
    id: '/events_/conferences_/cieft_/current-year_/registration',
    path: '/events/conferences/cieft/current-year/registration',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute =
  ResearchPublicationsDialogueFrancophonesCallsPastIndexRouteImport.update({
    id: '/research_/publications_/dialogue-francophones_/calls_/past/',
    path: '/research/publications/dialogue-francophones/calls/past/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute =
  ResearchPublicationsDialogueFrancophonesCallsFutureIndexRouteImport.update({
    id: '/research_/publications_/dialogue-francophones_/calls_/future/',
    path: '/research/publications/dialogue-francophones/calls/future/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute =
  ResearchPublicationsAgapesFrancophonesCallsPastIndexRouteImport.update({
    id: '/research_/publications_/agapes-francophones_/calls_/past/',
    path: '/research/publications/agapes-francophones/calls/past/',
    getParentRoute: () => rootRouteImport,
  } as any);
const ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute =
  ResearchPublicationsAgapesFrancophonesCallsFutureIndexRouteImport.update({
    id: '/research_/publications_/agapes-francophones_/calls_/future/',
    path: '/research/publications/agapes-francophones/calls/future/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRoute =
  EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRouteImport.update(
    {
      id: '/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners/',
      path: '/events/conferences/francophones-studies/current-year/organizers-and-partners/',
      getParentRoute: () => rootRouteImport,
    } as any
  );
const EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRoute =
  EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRouteImport.update({
    id: '/events_/conferences_/francophones-studies_/current-year_/events/',
    path: '/events/conferences/francophones-studies/current-year/events/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRoute =
  EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRouteImport.update({
    id: '/events_/conferences_/francophones-studies_/current-year_/calls/',
    path: '/events/conferences/francophones-studies/current-year/calls/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesCieftCurrentYearScientificCommitteeIndexRoute =
  EventsConferencesCieftCurrentYearScientificCommitteeIndexRouteImport.update({
    id: '/events_/conferences_/cieft_/current-year_/scientific-committee/',
    path: '/events/conferences/cieft/current-year/scientific-committee/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRoute =
  EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRouteImport.update(
    {
      id: '/events_/conferences_/cieft_/current-year_/organizers-and-partners/',
      path: '/events/conferences/cieft/current-year/organizers-and-partners/',
      getParentRoute: () => rootRouteImport,
    } as any
  );
const EventsConferencesCieftCurrentYearInfoIndexRoute =
  EventsConferencesCieftCurrentYearInfoIndexRouteImport.update({
    id: '/events_/conferences_/cieft_/current-year_/info/',
    path: '/events/conferences/cieft/current-year/info/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesCieftCurrentYearEventsIndexRoute =
  EventsConferencesCieftCurrentYearEventsIndexRouteImport.update({
    id: '/events_/conferences_/cieft_/current-year_/events/',
    path: '/events/conferences/cieft/current-year/events/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesCieftCurrentYearCallsIndexRoute =
  EventsConferencesCieftCurrentYearCallsIndexRouteImport.update({
    id: '/events_/conferences_/cieft_/current-year_/calls/',
    path: '/events/conferences/cieft/current-year/calls/',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRoute =
  EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRouteImport.update({
    id: '/events_/conferences_/francophones-studies_/current-year_/info/info',
    path: '/events/conferences/francophones-studies/current-year/info/info',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRoute =
  EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRouteImport.update(
    {
      id: '/events_/conferences_/francophones-studies_/current-year_/events/archive',
      path: '/events/conferences/francophones-studies/current-year/events/archive',
      getParentRoute: () => rootRouteImport,
    } as any
  );
const EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRoute =
  EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRouteImport.update(
    {
      id: '/events_/conferences_/francophones-studies_/current-year_/committee/scientific-committee',
      path: '/events/conferences/francophones-studies/current-year/committee/scientific-committee',
      getParentRoute: () => rootRouteImport,
    } as any
  );
const EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRoute =
  EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRouteImport.update(
    {
      id: '/events_/conferences_/francophones-studies_/current-year_/calls/archive',
      path: '/events/conferences/francophones-studies/current-year/calls/archive',
      getParentRoute: () => rootRouteImport,
    } as any
  );
const EventsConferencesCieftCurrentYearInfoArchiveRoute =
  EventsConferencesCieftCurrentYearInfoArchiveRouteImport.update({
    id: '/events_/conferences_/cieft_/current-year_/info/archive',
    path: '/events/conferences/cieft/current-year/info/archive',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesCieftCurrentYearEventsArchiveRoute =
  EventsConferencesCieftCurrentYearEventsArchiveRouteImport.update({
    id: '/events_/conferences_/cieft_/current-year_/events/archive',
    path: '/events/conferences/cieft/current-year/events/archive',
    getParentRoute: () => rootRouteImport,
  } as any);
const EventsConferencesCieftCurrentYearCallsArchiveRoute =
  EventsConferencesCieftCurrentYearCallsArchiveRouteImport.update({
    id: '/events_/conferences_/cieft_/current-year_/calls/archive',
    path: '/events/conferences/cieft/current-year/calls/archive',
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute;
  '/contact': typeof ContactRouteRoute;
  '/login': typeof LoginRouteRoute;
  '/announcements': typeof AnnouncementsIndexRoute;
  '/events/phd-theses/archive': typeof EventsPhdThesesArchiveRoute;
  '/events/round-tables/archive': typeof EventsRoundTablesArchiveRoute;
  '/about/description-and-objectives': typeof AboutDescriptionAndObjectivesIndexRoute;
  '/about/history': typeof AboutHistoryIndexRoute;
  '/about/members': typeof AboutMembersIndexRoute;
  '/about/partners': typeof AboutPartnersIndexRoute;
  '/events/phd-theses': typeof EventsPhdThesesIndexRoute;
  '/events/round-tables': typeof EventsRoundTablesIndexRoute;
  '/research/projects': typeof ResearchProjectsIndexRoute;
  '/events/conferences/lingvistic-francophones': typeof EventsConferencesLingvisticFrancophonesIndexRoute;
  '/research/publications/lingvistic-conferences': typeof ResearchPublicationsLingvisticConferencesIndexRoute;
  '/research/publications/members-publications': typeof ResearchPublicationsMembersPublicationsIndexRoute;
  '/research/publications/translations': typeof ResearchPublicationsTranslationsIndexRoute;
  '/events/conferences/cieft/current-year/registration': typeof EventsConferencesCieftCurrentYearRegistrationRoute;
  '/events/conferences/cieft/previous-editions/$year': typeof EventsConferencesCieftPreviousEditionsYearRoute;
  '/events/conferences/francophones-studies/current-year/registration': typeof EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute;
  '/events/conferences/francophones-studies/previous-editions/$year': typeof EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute;
  '/research/publications/dialogue-francophones/calls/$callId': typeof ResearchPublicationsDialogueFrancophonesCallsCallIdRoute;
  '/research/publications/dialogue-francophones/registration/registration': typeof ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute;
  '/research/publications/dialogue-francophones/volumes/$volumeId': typeof ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute;
  '/events/conferences/cieft/previous-editions': typeof EventsConferencesCieftPreviousEditionsIndexRoute;
  '/events/conferences/francophones-studies/previous-editions': typeof EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute;
  '/research/publications/agapes-francophones/about': typeof ResearchPublicationsAgapesFrancophonesAboutIndexRoute;
  '/research/publications/agapes-francophones/committees': typeof ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute;
  '/research/publications/agapes-francophones/editorial-policy': typeof ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute;
  '/research/publications/agapes-francophones/indexing': typeof ResearchPublicationsAgapesFrancophonesIndexingIndexRoute;
  '/research/publications/agapes-francophones/volumes': typeof ResearchPublicationsAgapesFrancophonesVolumesIndexRoute;
  '/research/publications/dialogue-francophones/about': typeof ResearchPublicationsDialogueFrancophonesAboutIndexRoute;
  '/research/publications/dialogue-francophones/committees': typeof ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute;
  '/research/publications/dialogue-francophones/editorial-policy': typeof ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute;
  '/research/publications/dialogue-francophones/indexing': typeof ResearchPublicationsDialogueFrancophonesIndexingIndexRoute;
  '/research/publications/dialogue-francophones/volumes': typeof ResearchPublicationsDialogueFrancophonesVolumesIndexRoute;
  '/events/conferences/cieft/current-year/calls/archive': typeof EventsConferencesCieftCurrentYearCallsArchiveRoute;
  '/events/conferences/cieft/current-year/events/archive': typeof EventsConferencesCieftCurrentYearEventsArchiveRoute;
  '/events/conferences/cieft/current-year/info/archive': typeof EventsConferencesCieftCurrentYearInfoArchiveRoute;
  '/events/conferences/francophones-studies/current-year/calls/archive': typeof EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRoute;
  '/events/conferences/francophones-studies/current-year/committee/scientific-committee': typeof EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRoute;
  '/events/conferences/francophones-studies/current-year/events/archive': typeof EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRoute;
  '/events/conferences/francophones-studies/current-year/info/info': typeof EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRoute;
  '/events/conferences/cieft/current-year/calls': typeof EventsConferencesCieftCurrentYearCallsIndexRoute;
  '/events/conferences/cieft/current-year/events': typeof EventsConferencesCieftCurrentYearEventsIndexRoute;
  '/events/conferences/cieft/current-year/info': typeof EventsConferencesCieftCurrentYearInfoIndexRoute;
  '/events/conferences/cieft/current-year/organizers-and-partners': typeof EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRoute;
  '/events/conferences/cieft/current-year/scientific-committee': typeof EventsConferencesCieftCurrentYearScientificCommitteeIndexRoute;
  '/events/conferences/francophones-studies/current-year/calls': typeof EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRoute;
  '/events/conferences/francophones-studies/current-year/events': typeof EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRoute;
  '/events/conferences/francophones-studies/current-year/organizers-and-partners': typeof EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRoute;
  '/research/publications/agapes-francophones/calls/future': typeof ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute;
  '/research/publications/agapes-francophones/calls/past': typeof ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute;
  '/research/publications/dialogue-francophones/calls/future': typeof ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute;
  '/research/publications/dialogue-francophones/calls/past': typeof ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute;
  '/contact': typeof ContactRouteRoute;
  '/login': typeof LoginRouteRoute;
  '/announcements': typeof AnnouncementsIndexRoute;
  '/events/phd-theses/archive': typeof EventsPhdThesesArchiveRoute;
  '/events/round-tables/archive': typeof EventsRoundTablesArchiveRoute;
  '/about/description-and-objectives': typeof AboutDescriptionAndObjectivesIndexRoute;
  '/about/history': typeof AboutHistoryIndexRoute;
  '/about/members': typeof AboutMembersIndexRoute;
  '/about/partners': typeof AboutPartnersIndexRoute;
  '/events/phd-theses': typeof EventsPhdThesesIndexRoute;
  '/events/round-tables': typeof EventsRoundTablesIndexRoute;
  '/research/projects': typeof ResearchProjectsIndexRoute;
  '/events/conferences/lingvistic-francophones': typeof EventsConferencesLingvisticFrancophonesIndexRoute;
  '/research/publications/lingvistic-conferences': typeof ResearchPublicationsLingvisticConferencesIndexRoute;
  '/research/publications/members-publications': typeof ResearchPublicationsMembersPublicationsIndexRoute;
  '/research/publications/translations': typeof ResearchPublicationsTranslationsIndexRoute;
  '/events/conferences/cieft/current-year/registration': typeof EventsConferencesCieftCurrentYearRegistrationRoute;
  '/events/conferences/cieft/previous-editions/$year': typeof EventsConferencesCieftPreviousEditionsYearRoute;
  '/events/conferences/francophones-studies/current-year/registration': typeof EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute;
  '/events/conferences/francophones-studies/previous-editions/$year': typeof EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute;
  '/research/publications/dialogue-francophones/calls/$callId': typeof ResearchPublicationsDialogueFrancophonesCallsCallIdRoute;
  '/research/publications/dialogue-francophones/registration/registration': typeof ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute;
  '/research/publications/dialogue-francophones/volumes/$volumeId': typeof ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute;
  '/events/conferences/cieft/previous-editions': typeof EventsConferencesCieftPreviousEditionsIndexRoute;
  '/events/conferences/francophones-studies/previous-editions': typeof EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute;
  '/research/publications/agapes-francophones/about': typeof ResearchPublicationsAgapesFrancophonesAboutIndexRoute;
  '/research/publications/agapes-francophones/committees': typeof ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute;
  '/research/publications/agapes-francophones/editorial-policy': typeof ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute;
  '/research/publications/agapes-francophones/indexing': typeof ResearchPublicationsAgapesFrancophonesIndexingIndexRoute;
  '/research/publications/agapes-francophones/volumes': typeof ResearchPublicationsAgapesFrancophonesVolumesIndexRoute;
  '/research/publications/dialogue-francophones/about': typeof ResearchPublicationsDialogueFrancophonesAboutIndexRoute;
  '/research/publications/dialogue-francophones/committees': typeof ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute;
  '/research/publications/dialogue-francophones/editorial-policy': typeof ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute;
  '/research/publications/dialogue-francophones/indexing': typeof ResearchPublicationsDialogueFrancophonesIndexingIndexRoute;
  '/research/publications/dialogue-francophones/volumes': typeof ResearchPublicationsDialogueFrancophonesVolumesIndexRoute;
  '/events/conferences/cieft/current-year/calls/archive': typeof EventsConferencesCieftCurrentYearCallsArchiveRoute;
  '/events/conferences/cieft/current-year/events/archive': typeof EventsConferencesCieftCurrentYearEventsArchiveRoute;
  '/events/conferences/cieft/current-year/info/archive': typeof EventsConferencesCieftCurrentYearInfoArchiveRoute;
  '/events/conferences/francophones-studies/current-year/calls/archive': typeof EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRoute;
  '/events/conferences/francophones-studies/current-year/committee/scientific-committee': typeof EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRoute;
  '/events/conferences/francophones-studies/current-year/events/archive': typeof EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRoute;
  '/events/conferences/francophones-studies/current-year/info/info': typeof EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRoute;
  '/events/conferences/cieft/current-year/calls': typeof EventsConferencesCieftCurrentYearCallsIndexRoute;
  '/events/conferences/cieft/current-year/events': typeof EventsConferencesCieftCurrentYearEventsIndexRoute;
  '/events/conferences/cieft/current-year/info': typeof EventsConferencesCieftCurrentYearInfoIndexRoute;
  '/events/conferences/cieft/current-year/organizers-and-partners': typeof EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRoute;
  '/events/conferences/cieft/current-year/scientific-committee': typeof EventsConferencesCieftCurrentYearScientificCommitteeIndexRoute;
  '/events/conferences/francophones-studies/current-year/calls': typeof EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRoute;
  '/events/conferences/francophones-studies/current-year/events': typeof EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRoute;
  '/events/conferences/francophones-studies/current-year/organizers-and-partners': typeof EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRoute;
  '/research/publications/agapes-francophones/calls/future': typeof ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute;
  '/research/publications/agapes-francophones/calls/past': typeof ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute;
  '/research/publications/dialogue-francophones/calls/future': typeof ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute;
  '/research/publications/dialogue-francophones/calls/past': typeof ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRouteRoute;
  '/contact': typeof ContactRouteRoute;
  '/login': typeof LoginRouteRoute;
  '/announcements/': typeof AnnouncementsIndexRoute;
  '/events_/phd-theses/archive': typeof EventsPhdThesesArchiveRoute;
  '/events_/round-tables/archive': typeof EventsRoundTablesArchiveRoute;
  '/about_/description-and-objectives/': typeof AboutDescriptionAndObjectivesIndexRoute;
  '/about_/history/': typeof AboutHistoryIndexRoute;
  '/about_/members/': typeof AboutMembersIndexRoute;
  '/about_/partners/': typeof AboutPartnersIndexRoute;
  '/events_/phd-theses/': typeof EventsPhdThesesIndexRoute;
  '/events_/round-tables/': typeof EventsRoundTablesIndexRoute;
  '/research_/projects/': typeof ResearchProjectsIndexRoute;
  '/events_/conferences_/lingvistic-francophones/': typeof EventsConferencesLingvisticFrancophonesIndexRoute;
  '/research_/publications_/lingvistic-conferences/': typeof ResearchPublicationsLingvisticConferencesIndexRoute;
  '/research_/publications_/members-publications/': typeof ResearchPublicationsMembersPublicationsIndexRoute;
  '/research_/publications_/translations/': typeof ResearchPublicationsTranslationsIndexRoute;
  '/events_/conferences_/cieft_/current-year_/registration': typeof EventsConferencesCieftCurrentYearRegistrationRoute;
  '/events_/conferences_/cieft_/previous-editions_/$year': typeof EventsConferencesCieftPreviousEditionsYearRoute;
  '/events_/conferences_/francophones-studies_/current-year_/registration': typeof EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute;
  '/events_/conferences_/francophones-studies_/previous-editions_/$year': typeof EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute;
  '/research_/publications_/dialogue-francophones_/calls_/$callId': typeof ResearchPublicationsDialogueFrancophonesCallsCallIdRoute;
  '/research_/publications_/dialogue-francophones_/registration/registration': typeof ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute;
  '/research_/publications_/dialogue-francophones_/volumes/$volumeId': typeof ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute;
  '/events_/conferences_/cieft_/previous-editions_/': typeof EventsConferencesCieftPreviousEditionsIndexRoute;
  '/events_/conferences_/francophones-studies_/previous-editions_/': typeof EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute;
  '/research_/publications_/agapes-francophones_/about/': typeof ResearchPublicationsAgapesFrancophonesAboutIndexRoute;
  '/research_/publications_/agapes-francophones_/committees/': typeof ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute;
  '/research_/publications_/agapes-francophones_/editorial-policy/': typeof ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute;
  '/research_/publications_/agapes-francophones_/indexing/': typeof ResearchPublicationsAgapesFrancophonesIndexingIndexRoute;
  '/research_/publications_/agapes-francophones_/volumes/': typeof ResearchPublicationsAgapesFrancophonesVolumesIndexRoute;
  '/research_/publications_/dialogue-francophones_/about/': typeof ResearchPublicationsDialogueFrancophonesAboutIndexRoute;
  '/research_/publications_/dialogue-francophones_/committees/': typeof ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute;
  '/research_/publications_/dialogue-francophones_/editorial-policy/': typeof ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute;
  '/research_/publications_/dialogue-francophones_/indexing/': typeof ResearchPublicationsDialogueFrancophonesIndexingIndexRoute;
  '/research_/publications_/dialogue-francophones_/volumes/': typeof ResearchPublicationsDialogueFrancophonesVolumesIndexRoute;
  '/events_/conferences_/cieft_/current-year_/calls/archive': typeof EventsConferencesCieftCurrentYearCallsArchiveRoute;
  '/events_/conferences_/cieft_/current-year_/events/archive': typeof EventsConferencesCieftCurrentYearEventsArchiveRoute;
  '/events_/conferences_/cieft_/current-year_/info/archive': typeof EventsConferencesCieftCurrentYearInfoArchiveRoute;
  '/events_/conferences_/francophones-studies_/current-year_/calls/archive': typeof EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRoute;
  '/events_/conferences_/francophones-studies_/current-year_/committee/scientific-committee': typeof EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRoute;
  '/events_/conferences_/francophones-studies_/current-year_/events/archive': typeof EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRoute;
  '/events_/conferences_/francophones-studies_/current-year_/info/info': typeof EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRoute;
  '/events_/conferences_/cieft_/current-year_/calls/': typeof EventsConferencesCieftCurrentYearCallsIndexRoute;
  '/events_/conferences_/cieft_/current-year_/events/': typeof EventsConferencesCieftCurrentYearEventsIndexRoute;
  '/events_/conferences_/cieft_/current-year_/info/': typeof EventsConferencesCieftCurrentYearInfoIndexRoute;
  '/events_/conferences_/cieft_/current-year_/organizers-and-partners/': typeof EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRoute;
  '/events_/conferences_/cieft_/current-year_/scientific-committee/': typeof EventsConferencesCieftCurrentYearScientificCommitteeIndexRoute;
  '/events_/conferences_/francophones-studies_/current-year_/calls/': typeof EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRoute;
  '/events_/conferences_/francophones-studies_/current-year_/events/': typeof EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRoute;
  '/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners/': typeof EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRoute;
  '/research_/publications_/agapes-francophones_/calls_/future/': typeof ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute;
  '/research_/publications_/agapes-francophones_/calls_/past/': typeof ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute;
  '/research_/publications_/dialogue-francophones_/calls_/future/': typeof ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute;
  '/research_/publications_/dialogue-francophones_/calls_/past/': typeof ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/announcements'
    | '/events/phd-theses/archive'
    | '/events/round-tables/archive'
    | '/about/description-and-objectives'
    | '/about/history'
    | '/about/members'
    | '/about/partners'
    | '/events/phd-theses'
    | '/events/round-tables'
    | '/research/projects'
    | '/events/conferences/lingvistic-francophones'
    | '/research/publications/lingvistic-conferences'
    | '/research/publications/members-publications'
    | '/research/publications/translations'
    | '/events/conferences/cieft/current-year/registration'
    | '/events/conferences/cieft/previous-editions/$year'
    | '/events/conferences/francophones-studies/current-year/registration'
    | '/events/conferences/francophones-studies/previous-editions/$year'
    | '/research/publications/dialogue-francophones/calls/$callId'
    | '/research/publications/dialogue-francophones/registration/registration'
    | '/research/publications/dialogue-francophones/volumes/$volumeId'
    | '/events/conferences/cieft/previous-editions'
    | '/events/conferences/francophones-studies/previous-editions'
    | '/research/publications/agapes-francophones/about'
    | '/research/publications/agapes-francophones/committees'
    | '/research/publications/agapes-francophones/editorial-policy'
    | '/research/publications/agapes-francophones/indexing'
    | '/research/publications/agapes-francophones/volumes'
    | '/research/publications/dialogue-francophones/about'
    | '/research/publications/dialogue-francophones/committees'
    | '/research/publications/dialogue-francophones/editorial-policy'
    | '/research/publications/dialogue-francophones/indexing'
    | '/research/publications/dialogue-francophones/volumes'
    | '/events/conferences/cieft/current-year/calls/archive'
    | '/events/conferences/cieft/current-year/events/archive'
    | '/events/conferences/cieft/current-year/info/archive'
    | '/events/conferences/francophones-studies/current-year/calls/archive'
    | '/events/conferences/francophones-studies/current-year/committee/scientific-committee'
    | '/events/conferences/francophones-studies/current-year/events/archive'
    | '/events/conferences/francophones-studies/current-year/info/info'
    | '/events/conferences/cieft/current-year/calls'
    | '/events/conferences/cieft/current-year/events'
    | '/events/conferences/cieft/current-year/info'
    | '/events/conferences/cieft/current-year/organizers-and-partners'
    | '/events/conferences/cieft/current-year/scientific-committee'
    | '/events/conferences/francophones-studies/current-year/calls'
    | '/events/conferences/francophones-studies/current-year/events'
    | '/events/conferences/francophones-studies/current-year/organizers-and-partners'
    | '/research/publications/agapes-francophones/calls/future'
    | '/research/publications/agapes-francophones/calls/past'
    | '/research/publications/dialogue-francophones/calls/future'
    | '/research/publications/dialogue-francophones/calls/past';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/announcements'
    | '/events/phd-theses/archive'
    | '/events/round-tables/archive'
    | '/about/description-and-objectives'
    | '/about/history'
    | '/about/members'
    | '/about/partners'
    | '/events/phd-theses'
    | '/events/round-tables'
    | '/research/projects'
    | '/events/conferences/lingvistic-francophones'
    | '/research/publications/lingvistic-conferences'
    | '/research/publications/members-publications'
    | '/research/publications/translations'
    | '/events/conferences/cieft/current-year/registration'
    | '/events/conferences/cieft/previous-editions/$year'
    | '/events/conferences/francophones-studies/current-year/registration'
    | '/events/conferences/francophones-studies/previous-editions/$year'
    | '/research/publications/dialogue-francophones/calls/$callId'
    | '/research/publications/dialogue-francophones/registration/registration'
    | '/research/publications/dialogue-francophones/volumes/$volumeId'
    | '/events/conferences/cieft/previous-editions'
    | '/events/conferences/francophones-studies/previous-editions'
    | '/research/publications/agapes-francophones/about'
    | '/research/publications/agapes-francophones/committees'
    | '/research/publications/agapes-francophones/editorial-policy'
    | '/research/publications/agapes-francophones/indexing'
    | '/research/publications/agapes-francophones/volumes'
    | '/research/publications/dialogue-francophones/about'
    | '/research/publications/dialogue-francophones/committees'
    | '/research/publications/dialogue-francophones/editorial-policy'
    | '/research/publications/dialogue-francophones/indexing'
    | '/research/publications/dialogue-francophones/volumes'
    | '/events/conferences/cieft/current-year/calls/archive'
    | '/events/conferences/cieft/current-year/events/archive'
    | '/events/conferences/cieft/current-year/info/archive'
    | '/events/conferences/francophones-studies/current-year/calls/archive'
    | '/events/conferences/francophones-studies/current-year/committee/scientific-committee'
    | '/events/conferences/francophones-studies/current-year/events/archive'
    | '/events/conferences/francophones-studies/current-year/info/info'
    | '/events/conferences/cieft/current-year/calls'
    | '/events/conferences/cieft/current-year/events'
    | '/events/conferences/cieft/current-year/info'
    | '/events/conferences/cieft/current-year/organizers-and-partners'
    | '/events/conferences/cieft/current-year/scientific-committee'
    | '/events/conferences/francophones-studies/current-year/calls'
    | '/events/conferences/francophones-studies/current-year/events'
    | '/events/conferences/francophones-studies/current-year/organizers-and-partners'
    | '/research/publications/agapes-francophones/calls/future'
    | '/research/publications/agapes-francophones/calls/past'
    | '/research/publications/dialogue-francophones/calls/future'
    | '/research/publications/dialogue-francophones/calls/past';
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/login'
    | '/announcements/'
    | '/events_/phd-theses/archive'
    | '/events_/round-tables/archive'
    | '/about_/description-and-objectives/'
    | '/about_/history/'
    | '/about_/members/'
    | '/about_/partners/'
    | '/events_/phd-theses/'
    | '/events_/round-tables/'
    | '/research_/projects/'
    | '/events_/conferences_/lingvistic-francophones/'
    | '/research_/publications_/lingvistic-conferences/'
    | '/research_/publications_/members-publications/'
    | '/research_/publications_/translations/'
    | '/events_/conferences_/cieft_/current-year_/registration'
    | '/events_/conferences_/cieft_/previous-editions_/$year'
    | '/events_/conferences_/francophones-studies_/current-year_/registration'
    | '/events_/conferences_/francophones-studies_/previous-editions_/$year'
    | '/research_/publications_/dialogue-francophones_/calls_/$callId'
    | '/research_/publications_/dialogue-francophones_/registration/registration'
    | '/research_/publications_/dialogue-francophones_/volumes/$volumeId'
    | '/events_/conferences_/cieft_/previous-editions_/'
    | '/events_/conferences_/francophones-studies_/previous-editions_/'
    | '/research_/publications_/agapes-francophones_/about/'
    | '/research_/publications_/agapes-francophones_/committees/'
    | '/research_/publications_/agapes-francophones_/editorial-policy/'
    | '/research_/publications_/agapes-francophones_/indexing/'
    | '/research_/publications_/agapes-francophones_/volumes/'
    | '/research_/publications_/dialogue-francophones_/about/'
    | '/research_/publications_/dialogue-francophones_/committees/'
    | '/research_/publications_/dialogue-francophones_/editorial-policy/'
    | '/research_/publications_/dialogue-francophones_/indexing/'
    | '/research_/publications_/dialogue-francophones_/volumes/'
    | '/events_/conferences_/cieft_/current-year_/calls/archive'
    | '/events_/conferences_/cieft_/current-year_/events/archive'
    | '/events_/conferences_/cieft_/current-year_/info/archive'
    | '/events_/conferences_/francophones-studies_/current-year_/calls/archive'
    | '/events_/conferences_/francophones-studies_/current-year_/committee/scientific-committee'
    | '/events_/conferences_/francophones-studies_/current-year_/events/archive'
    | '/events_/conferences_/francophones-studies_/current-year_/info/info'
    | '/events_/conferences_/cieft_/current-year_/calls/'
    | '/events_/conferences_/cieft_/current-year_/events/'
    | '/events_/conferences_/cieft_/current-year_/info/'
    | '/events_/conferences_/cieft_/current-year_/organizers-and-partners/'
    | '/events_/conferences_/cieft_/current-year_/scientific-committee/'
    | '/events_/conferences_/francophones-studies_/current-year_/calls/'
    | '/events_/conferences_/francophones-studies_/current-year_/events/'
    | '/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners/'
    | '/research_/publications_/agapes-francophones_/calls_/future/'
    | '/research_/publications_/agapes-francophones_/calls_/past/'
    | '/research_/publications_/dialogue-francophones_/calls_/future/'
    | '/research_/publications_/dialogue-francophones_/calls_/past/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute;
  ContactRouteRoute: typeof ContactRouteRoute;
  LoginRouteRoute: typeof LoginRouteRoute;
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute;
  EventsPhdThesesArchiveRoute: typeof EventsPhdThesesArchiveRoute;
  EventsRoundTablesArchiveRoute: typeof EventsRoundTablesArchiveRoute;
  AboutDescriptionAndObjectivesIndexRoute: typeof AboutDescriptionAndObjectivesIndexRoute;
  AboutHistoryIndexRoute: typeof AboutHistoryIndexRoute;
  AboutMembersIndexRoute: typeof AboutMembersIndexRoute;
  AboutPartnersIndexRoute: typeof AboutPartnersIndexRoute;
  EventsPhdThesesIndexRoute: typeof EventsPhdThesesIndexRoute;
  EventsRoundTablesIndexRoute: typeof EventsRoundTablesIndexRoute;
  ResearchProjectsIndexRoute: typeof ResearchProjectsIndexRoute;
  EventsConferencesLingvisticFrancophonesIndexRoute: typeof EventsConferencesLingvisticFrancophonesIndexRoute;
  ResearchPublicationsLingvisticConferencesIndexRoute: typeof ResearchPublicationsLingvisticConferencesIndexRoute;
  ResearchPublicationsMembersPublicationsIndexRoute: typeof ResearchPublicationsMembersPublicationsIndexRoute;
  ResearchPublicationsTranslationsIndexRoute: typeof ResearchPublicationsTranslationsIndexRoute;
  EventsConferencesCieftCurrentYearRegistrationRoute: typeof EventsConferencesCieftCurrentYearRegistrationRoute;
  EventsConferencesCieftPreviousEditionsYearRoute: typeof EventsConferencesCieftPreviousEditionsYearRoute;
  EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute;
  EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute: typeof EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute;
  ResearchPublicationsDialogueFrancophonesCallsCallIdRoute: typeof ResearchPublicationsDialogueFrancophonesCallsCallIdRoute;
  ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute: typeof ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute;
  ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute: typeof ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute;
  EventsConferencesCieftPreviousEditionsIndexRoute: typeof EventsConferencesCieftPreviousEditionsIndexRoute;
  EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute: typeof EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute;
  ResearchPublicationsAgapesFrancophonesAboutIndexRoute: typeof ResearchPublicationsAgapesFrancophonesAboutIndexRoute;
  ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute: typeof ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute;
  ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute: typeof ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute;
  ResearchPublicationsAgapesFrancophonesIndexingIndexRoute: typeof ResearchPublicationsAgapesFrancophonesIndexingIndexRoute;
  ResearchPublicationsAgapesFrancophonesVolumesIndexRoute: typeof ResearchPublicationsAgapesFrancophonesVolumesIndexRoute;
  ResearchPublicationsDialogueFrancophonesAboutIndexRoute: typeof ResearchPublicationsDialogueFrancophonesAboutIndexRoute;
  ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute: typeof ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute;
  ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute: typeof ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute;
  ResearchPublicationsDialogueFrancophonesIndexingIndexRoute: typeof ResearchPublicationsDialogueFrancophonesIndexingIndexRoute;
  ResearchPublicationsDialogueFrancophonesVolumesIndexRoute: typeof ResearchPublicationsDialogueFrancophonesVolumesIndexRoute;
  EventsConferencesCieftCurrentYearCallsArchiveRoute: typeof EventsConferencesCieftCurrentYearCallsArchiveRoute;
  EventsConferencesCieftCurrentYearEventsArchiveRoute: typeof EventsConferencesCieftCurrentYearEventsArchiveRoute;
  EventsConferencesCieftCurrentYearInfoArchiveRoute: typeof EventsConferencesCieftCurrentYearInfoArchiveRoute;
  EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRoute;
  EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRoute;
  EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRoute;
  EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRoute;
  EventsConferencesCieftCurrentYearCallsIndexRoute: typeof EventsConferencesCieftCurrentYearCallsIndexRoute;
  EventsConferencesCieftCurrentYearEventsIndexRoute: typeof EventsConferencesCieftCurrentYearEventsIndexRoute;
  EventsConferencesCieftCurrentYearInfoIndexRoute: typeof EventsConferencesCieftCurrentYearInfoIndexRoute;
  EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRoute: typeof EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRoute;
  EventsConferencesCieftCurrentYearScientificCommitteeIndexRoute: typeof EventsConferencesCieftCurrentYearScientificCommitteeIndexRoute;
  EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRoute;
  EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRoute;
  EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRoute;
  ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute: typeof ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute;
  ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute: typeof ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute;
  ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute: typeof ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute;
  ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute: typeof ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/contact': {
      id: '/contact';
      path: '/contact';
      fullPath: '/contact';
      preLoaderRoute: typeof ContactRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/announcements/': {
      id: '/announcements/';
      path: '/announcements';
      fullPath: '/announcements';
      preLoaderRoute: typeof AnnouncementsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/projects/': {
      id: '/research_/projects/';
      path: '/research/projects';
      fullPath: '/research/projects';
      preLoaderRoute: typeof ResearchProjectsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/round-tables/': {
      id: '/events_/round-tables/';
      path: '/events/round-tables';
      fullPath: '/events/round-tables';
      preLoaderRoute: typeof EventsRoundTablesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/phd-theses/': {
      id: '/events_/phd-theses/';
      path: '/events/phd-theses';
      fullPath: '/events/phd-theses';
      preLoaderRoute: typeof EventsPhdThesesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about_/partners/': {
      id: '/about_/partners/';
      path: '/about/partners';
      fullPath: '/about/partners';
      preLoaderRoute: typeof AboutPartnersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about_/members/': {
      id: '/about_/members/';
      path: '/about/members';
      fullPath: '/about/members';
      preLoaderRoute: typeof AboutMembersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about_/history/': {
      id: '/about_/history/';
      path: '/about/history';
      fullPath: '/about/history';
      preLoaderRoute: typeof AboutHistoryIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about_/description-and-objectives/': {
      id: '/about_/description-and-objectives/';
      path: '/about/description-and-objectives';
      fullPath: '/about/description-and-objectives';
      preLoaderRoute: typeof AboutDescriptionAndObjectivesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/round-tables/archive': {
      id: '/events_/round-tables/archive';
      path: '/events/round-tables/archive';
      fullPath: '/events/round-tables/archive';
      preLoaderRoute: typeof EventsRoundTablesArchiveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/phd-theses/archive': {
      id: '/events_/phd-theses/archive';
      path: '/events/phd-theses/archive';
      fullPath: '/events/phd-theses/archive';
      preLoaderRoute: typeof EventsPhdThesesArchiveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/translations/': {
      id: '/research_/publications_/translations/';
      path: '/research/publications/translations';
      fullPath: '/research/publications/translations';
      preLoaderRoute: typeof ResearchPublicationsTranslationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/members-publications/': {
      id: '/research_/publications_/members-publications/';
      path: '/research/publications/members-publications';
      fullPath: '/research/publications/members-publications';
      preLoaderRoute: typeof ResearchPublicationsMembersPublicationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/lingvistic-conferences/': {
      id: '/research_/publications_/lingvistic-conferences/';
      path: '/research/publications/lingvistic-conferences';
      fullPath: '/research/publications/lingvistic-conferences';
      preLoaderRoute: typeof ResearchPublicationsLingvisticConferencesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/lingvistic-francophones/': {
      id: '/events_/conferences_/lingvistic-francophones/';
      path: '/events/conferences/lingvistic-francophones';
      fullPath: '/events/conferences/lingvistic-francophones';
      preLoaderRoute: typeof EventsConferencesLingvisticFrancophonesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/dialogue-francophones_/volumes/': {
      id: '/research_/publications_/dialogue-francophones_/volumes/';
      path: '/research/publications/dialogue-francophones/volumes';
      fullPath: '/research/publications/dialogue-francophones/volumes';
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesVolumesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/dialogue-francophones_/indexing/': {
      id: '/research_/publications_/dialogue-francophones_/indexing/';
      path: '/research/publications/dialogue-francophones/indexing';
      fullPath: '/research/publications/dialogue-francophones/indexing';
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesIndexingIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/dialogue-francophones_/editorial-policy/': {
      id: '/research_/publications_/dialogue-francophones_/editorial-policy/';
      path: '/research/publications/dialogue-francophones/editorial-policy';
      fullPath: '/research/publications/dialogue-francophones/editorial-policy';
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/dialogue-francophones_/committees/': {
      id: '/research_/publications_/dialogue-francophones_/committees/';
      path: '/research/publications/dialogue-francophones/committees';
      fullPath: '/research/publications/dialogue-francophones/committees';
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesCommitteesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/dialogue-francophones_/about/': {
      id: '/research_/publications_/dialogue-francophones_/about/';
      path: '/research/publications/dialogue-francophones/about';
      fullPath: '/research/publications/dialogue-francophones/about';
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesAboutIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/agapes-francophones_/volumes/': {
      id: '/research_/publications_/agapes-francophones_/volumes/';
      path: '/research/publications/agapes-francophones/volumes';
      fullPath: '/research/publications/agapes-francophones/volumes';
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesVolumesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/agapes-francophones_/indexing/': {
      id: '/research_/publications_/agapes-francophones_/indexing/';
      path: '/research/publications/agapes-francophones/indexing';
      fullPath: '/research/publications/agapes-francophones/indexing';
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesIndexingIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/agapes-francophones_/editorial-policy/': {
      id: '/research_/publications_/agapes-francophones_/editorial-policy/';
      path: '/research/publications/agapes-francophones/editorial-policy';
      fullPath: '/research/publications/agapes-francophones/editorial-policy';
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/agapes-francophones_/committees/': {
      id: '/research_/publications_/agapes-francophones_/committees/';
      path: '/research/publications/agapes-francophones/committees';
      fullPath: '/research/publications/agapes-francophones/committees';
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesCommitteesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/agapes-francophones_/about/': {
      id: '/research_/publications_/agapes-francophones_/about/';
      path: '/research/publications/agapes-francophones/about';
      fullPath: '/research/publications/agapes-francophones/about';
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesAboutIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/francophones-studies_/previous-editions_/': {
      id: '/events_/conferences_/francophones-studies_/previous-editions_/';
      path: '/events/conferences/francophones-studies/previous-editions';
      fullPath: '/events/conferences/francophones-studies/previous-editions';
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesPreviousEditionsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/previous-editions_/': {
      id: '/events_/conferences_/cieft_/previous-editions_/';
      path: '/events/conferences/cieft/previous-editions';
      fullPath: '/events/conferences/cieft/previous-editions';
      preLoaderRoute: typeof EventsConferencesCieftPreviousEditionsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/dialogue-francophones_/volumes/$volumeId': {
      id: '/research_/publications_/dialogue-francophones_/volumes/$volumeId';
      path: '/research/publications/dialogue-francophones/volumes/$volumeId';
      fullPath: '/research/publications/dialogue-francophones/volumes/$volumeId';
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/dialogue-francophones_/registration/registration': {
      id: '/research_/publications_/dialogue-francophones_/registration/registration';
      path: '/research/publications/dialogue-francophones/registration/registration';
      fullPath: '/research/publications/dialogue-francophones/registration/registration';
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/dialogue-francophones_/calls_/$callId': {
      id: '/research_/publications_/dialogue-francophones_/calls_/$callId';
      path: '/research/publications/dialogue-francophones/calls/$callId';
      fullPath: '/research/publications/dialogue-francophones/calls/$callId';
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesCallsCallIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/francophones-studies_/previous-editions_/$year': {
      id: '/events_/conferences_/francophones-studies_/previous-editions_/$year';
      path: '/events/conferences/francophones-studies/previous-editions/$year';
      fullPath: '/events/conferences/francophones-studies/previous-editions/$year';
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesPreviousEditionsYearRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/francophones-studies_/current-year_/registration': {
      id: '/events_/conferences_/francophones-studies_/current-year_/registration';
      path: '/events/conferences/francophones-studies/current-year/registration';
      fullPath: '/events/conferences/francophones-studies/current-year/registration';
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearRegistrationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/previous-editions_/$year': {
      id: '/events_/conferences_/cieft_/previous-editions_/$year';
      path: '/events/conferences/cieft/previous-editions/$year';
      fullPath: '/events/conferences/cieft/previous-editions/$year';
      preLoaderRoute: typeof EventsConferencesCieftPreviousEditionsYearRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/current-year_/registration': {
      id: '/events_/conferences_/cieft_/current-year_/registration';
      path: '/events/conferences/cieft/current-year/registration';
      fullPath: '/events/conferences/cieft/current-year/registration';
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearRegistrationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/dialogue-francophones_/calls_/past/': {
      id: '/research_/publications_/dialogue-francophones_/calls_/past/';
      path: '/research/publications/dialogue-francophones/calls/past';
      fullPath: '/research/publications/dialogue-francophones/calls/past';
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesCallsPastIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/dialogue-francophones_/calls_/future/': {
      id: '/research_/publications_/dialogue-francophones_/calls_/future/';
      path: '/research/publications/dialogue-francophones/calls/future';
      fullPath: '/research/publications/dialogue-francophones/calls/future';
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesCallsFutureIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/agapes-francophones_/calls_/past/': {
      id: '/research_/publications_/agapes-francophones_/calls_/past/';
      path: '/research/publications/agapes-francophones/calls/past';
      fullPath: '/research/publications/agapes-francophones/calls/past';
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesCallsPastIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/research_/publications_/agapes-francophones_/calls_/future/': {
      id: '/research_/publications_/agapes-francophones_/calls_/future/';
      path: '/research/publications/agapes-francophones/calls/future';
      fullPath: '/research/publications/agapes-francophones/calls/future';
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesCallsFutureIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners/': {
      id: '/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners/';
      path: '/events/conferences/francophones-studies/current-year/organizers-and-partners';
      fullPath: '/events/conferences/francophones-studies/current-year/organizers-and-partners';
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/francophones-studies_/current-year_/events/': {
      id: '/events_/conferences_/francophones-studies_/current-year_/events/';
      path: '/events/conferences/francophones-studies/current-year/events';
      fullPath: '/events/conferences/francophones-studies/current-year/events';
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/francophones-studies_/current-year_/calls/': {
      id: '/events_/conferences_/francophones-studies_/current-year_/calls/';
      path: '/events/conferences/francophones-studies/current-year/calls';
      fullPath: '/events/conferences/francophones-studies/current-year/calls';
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/current-year_/scientific-committee/': {
      id: '/events_/conferences_/cieft_/current-year_/scientific-committee/';
      path: '/events/conferences/cieft/current-year/scientific-committee';
      fullPath: '/events/conferences/cieft/current-year/scientific-committee';
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearScientificCommitteeIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/current-year_/organizers-and-partners/': {
      id: '/events_/conferences_/cieft_/current-year_/organizers-and-partners/';
      path: '/events/conferences/cieft/current-year/organizers-and-partners';
      fullPath: '/events/conferences/cieft/current-year/organizers-and-partners';
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/current-year_/info/': {
      id: '/events_/conferences_/cieft_/current-year_/info/';
      path: '/events/conferences/cieft/current-year/info';
      fullPath: '/events/conferences/cieft/current-year/info';
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearInfoIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/current-year_/events/': {
      id: '/events_/conferences_/cieft_/current-year_/events/';
      path: '/events/conferences/cieft/current-year/events';
      fullPath: '/events/conferences/cieft/current-year/events';
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearEventsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/current-year_/calls/': {
      id: '/events_/conferences_/cieft_/current-year_/calls/';
      path: '/events/conferences/cieft/current-year/calls';
      fullPath: '/events/conferences/cieft/current-year/calls';
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearCallsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/francophones-studies_/current-year_/info/info': {
      id: '/events_/conferences_/francophones-studies_/current-year_/info/info';
      path: '/events/conferences/francophones-studies/current-year/info/info';
      fullPath: '/events/conferences/francophones-studies/current-year/info/info';
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/francophones-studies_/current-year_/events/archive': {
      id: '/events_/conferences_/francophones-studies_/current-year_/events/archive';
      path: '/events/conferences/francophones-studies/current-year/events/archive';
      fullPath: '/events/conferences/francophones-studies/current-year/events/archive';
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/francophones-studies_/current-year_/committee/scientific-committee': {
      id: '/events_/conferences_/francophones-studies_/current-year_/committee/scientific-committee';
      path: '/events/conferences/francophones-studies/current-year/committee/scientific-committee';
      fullPath: '/events/conferences/francophones-studies/current-year/committee/scientific-committee';
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/francophones-studies_/current-year_/calls/archive': {
      id: '/events_/conferences_/francophones-studies_/current-year_/calls/archive';
      path: '/events/conferences/francophones-studies/current-year/calls/archive';
      fullPath: '/events/conferences/francophones-studies/current-year/calls/archive';
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/current-year_/info/archive': {
      id: '/events_/conferences_/cieft_/current-year_/info/archive';
      path: '/events/conferences/cieft/current-year/info/archive';
      fullPath: '/events/conferences/cieft/current-year/info/archive';
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearInfoArchiveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/current-year_/events/archive': {
      id: '/events_/conferences_/cieft_/current-year_/events/archive';
      path: '/events/conferences/cieft/current-year/events/archive';
      fullPath: '/events/conferences/cieft/current-year/events/archive';
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearEventsArchiveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/events_/conferences_/cieft_/current-year_/calls/archive': {
      id: '/events_/conferences_/cieft_/current-year_/calls/archive';
      path: '/events/conferences/cieft/current-year/calls/archive';
      fullPath: '/events/conferences/cieft/current-year/calls/archive';
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearCallsArchiveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  ContactRouteRoute: ContactRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  EventsPhdThesesArchiveRoute: EventsPhdThesesArchiveRoute,
  EventsRoundTablesArchiveRoute: EventsRoundTablesArchiveRoute,
  AboutDescriptionAndObjectivesIndexRoute:
    AboutDescriptionAndObjectivesIndexRoute,
  AboutHistoryIndexRoute: AboutHistoryIndexRoute,
  AboutMembersIndexRoute: AboutMembersIndexRoute,
  AboutPartnersIndexRoute: AboutPartnersIndexRoute,
  EventsPhdThesesIndexRoute: EventsPhdThesesIndexRoute,
  EventsRoundTablesIndexRoute: EventsRoundTablesIndexRoute,
  ResearchProjectsIndexRoute: ResearchProjectsIndexRoute,
  EventsConferencesLingvisticFrancophonesIndexRoute:
    EventsConferencesLingvisticFrancophonesIndexRoute,
  ResearchPublicationsLingvisticConferencesIndexRoute:
    ResearchPublicationsLingvisticConferencesIndexRoute,
  ResearchPublicationsMembersPublicationsIndexRoute:
    ResearchPublicationsMembersPublicationsIndexRoute,
  ResearchPublicationsTranslationsIndexRoute:
    ResearchPublicationsTranslationsIndexRoute,
  EventsConferencesCieftCurrentYearRegistrationRoute:
    EventsConferencesCieftCurrentYearRegistrationRoute,
  EventsConferencesCieftPreviousEditionsYearRoute:
    EventsConferencesCieftPreviousEditionsYearRoute,
  EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute:
    EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute,
  EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute:
    EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute,
  ResearchPublicationsDialogueFrancophonesCallsCallIdRoute:
    ResearchPublicationsDialogueFrancophonesCallsCallIdRoute,
  ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute:
    ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute,
  ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute:
    ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute,
  EventsConferencesCieftPreviousEditionsIndexRoute:
    EventsConferencesCieftPreviousEditionsIndexRoute,
  EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute:
    EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute,
  ResearchPublicationsAgapesFrancophonesAboutIndexRoute:
    ResearchPublicationsAgapesFrancophonesAboutIndexRoute,
  ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute:
    ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute,
  ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute:
    ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute,
  ResearchPublicationsAgapesFrancophonesIndexingIndexRoute:
    ResearchPublicationsAgapesFrancophonesIndexingIndexRoute,
  ResearchPublicationsAgapesFrancophonesVolumesIndexRoute:
    ResearchPublicationsAgapesFrancophonesVolumesIndexRoute,
  ResearchPublicationsDialogueFrancophonesAboutIndexRoute:
    ResearchPublicationsDialogueFrancophonesAboutIndexRoute,
  ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute:
    ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute,
  ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute:
    ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute,
  ResearchPublicationsDialogueFrancophonesIndexingIndexRoute:
    ResearchPublicationsDialogueFrancophonesIndexingIndexRoute,
  ResearchPublicationsDialogueFrancophonesVolumesIndexRoute:
    ResearchPublicationsDialogueFrancophonesVolumesIndexRoute,
  EventsConferencesCieftCurrentYearCallsArchiveRoute:
    EventsConferencesCieftCurrentYearCallsArchiveRoute,
  EventsConferencesCieftCurrentYearEventsArchiveRoute:
    EventsConferencesCieftCurrentYearEventsArchiveRoute,
  EventsConferencesCieftCurrentYearInfoArchiveRoute:
    EventsConferencesCieftCurrentYearInfoArchiveRoute,
  EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRoute:
    EventsConferencesFrancophonesStudiesCurrentYearCallsArchiveRoute,
  EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRoute:
    EventsConferencesFrancophonesStudiesCurrentYearCommitteeScientificCommitteeRoute,
  EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRoute:
    EventsConferencesFrancophonesStudiesCurrentYearEventsArchiveRoute,
  EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRoute:
    EventsConferencesFrancophonesStudiesCurrentYearInfoInfoRoute,
  EventsConferencesCieftCurrentYearCallsIndexRoute:
    EventsConferencesCieftCurrentYearCallsIndexRoute,
  EventsConferencesCieftCurrentYearEventsIndexRoute:
    EventsConferencesCieftCurrentYearEventsIndexRoute,
  EventsConferencesCieftCurrentYearInfoIndexRoute:
    EventsConferencesCieftCurrentYearInfoIndexRoute,
  EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRoute:
    EventsConferencesCieftCurrentYearOrganizersAndPartnersIndexRoute,
  EventsConferencesCieftCurrentYearScientificCommitteeIndexRoute:
    EventsConferencesCieftCurrentYearScientificCommitteeIndexRoute,
  EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRoute:
    EventsConferencesFrancophonesStudiesCurrentYearCallsIndexRoute,
  EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRoute:
    EventsConferencesFrancophonesStudiesCurrentYearEventsIndexRoute,
  EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRoute:
    EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersIndexRoute,
  ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute:
    ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute,
  ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute:
    ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute,
  ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute:
    ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute,
  ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute:
    ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
