/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login/route'
import { Route as ContactRouteImport } from './routes/contact/route'
import { Route as IndexRouteImport } from './routes/index/route'
import { Route as AboutPartnersRouteImport } from './routes/about_/partners/route'
import { Route as ResearchProjectsIndexImport } from './routes/research_/projects/index'
import { Route as EventsRoundTablesIndexImport } from './routes/events_/round-tables/index'
import { Route as EventsPhdThesesIndexImport } from './routes/events_/phd-theses/index'
import { Route as AboutPartnersIndexImport } from './routes/about_/partners/index'
import { Route as AboutMembersIndexImport } from './routes/about_/members/index'
import { Route as AboutHistoryIndexImport } from './routes/about_/history/index'
import { Route as AboutDescriptionAndObjectivesIndexImport } from './routes/about_/description-and-objectives/index'
import { Route as ResearchPublicationsTranslationsIndexImport } from './routes/research_/publications_/translations/index'
import { Route as ResearchPublicationsMembersPublicationsIndexImport } from './routes/research_/publications_/members-publications/index'
import { Route as ResearchPublicationsLingvisticConferencesIndexImport } from './routes/research_/publications_/lingvistic-conferences/index'
import { Route as EventsConferencesLingvisticFrancophonesIndexImport } from './routes/events_/conferences_/lingvistic-francophones/index'
import { Route as ResearchPublicationsDialogueFrancophonesVolumesIndexImport } from './routes/research_/publications_/dialogue-francophones_/volumes/index'
import { Route as ResearchPublicationsDialogueFrancophonesIndexingIndexImport } from './routes/research_/publications_/dialogue-francophones_/indexing/index'
import { Route as ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexImport } from './routes/research_/publications_/dialogue-francophones_/editorial-policy/index'
import { Route as ResearchPublicationsDialogueFrancophonesCommitteesIndexImport } from './routes/research_/publications_/dialogue-francophones_/committees/index'
import { Route as ResearchPublicationsDialogueFrancophonesAboutIndexImport } from './routes/research_/publications_/dialogue-francophones_/about/index'
import { Route as ResearchPublicationsAgapesFrancophonesVolumesIndexImport } from './routes/research_/publications_/agapes-francophones_/volumes/index'
import { Route as ResearchPublicationsAgapesFrancophonesIndexingIndexImport } from './routes/research_/publications_/agapes-francophones_/indexing/index'
import { Route as ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexImport } from './routes/research_/publications_/agapes-francophones_/editorial-policy/index'
import { Route as ResearchPublicationsAgapesFrancophonesCommitteesIndexImport } from './routes/research_/publications_/agapes-francophones_/committees/index'
import { Route as ResearchPublicationsAgapesFrancophonesAboutIndexImport } from './routes/research_/publications_/agapes-francophones_/about/index'
import { Route as EventsConferencesFrancophonesStudiesPreviousEditionsIndexImport } from './routes/events_/conferences_/francophones-studies_/previous-editions_/index'
import { Route as EventsConferencesCieftPreviousEditionsIndexImport } from './routes/events_/conferences_/cieft_/previous-editions_/index'
import { Route as ResearchPublicationsDialogueFrancophonesVolumesVolumeIdImport } from './routes/research_/publications_/dialogue-francophones_/volumes/$volumeId'
import { Route as ResearchPublicationsDialogueFrancophonesRegistrationRegistrationImport } from './routes/research_/publications_/dialogue-francophones_/registration/registration'
import { Route as ResearchPublicationsDialogueFrancophonesCallsCallIdImport } from './routes/research_/publications_/dialogue-francophones_/calls_/$callId'
import { Route as EventsConferencesFrancophonesStudiesPreviousEditionsYearImport } from './routes/events_/conferences_/francophones-studies_/previous-editions_/$year'
import { Route as EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeImport } from './routes/events_/conferences_/francophones-studies_/current-year_/scientific-committee'
import { Route as EventsConferencesFrancophonesStudiesCurrentYearRegistrationImport } from './routes/events_/conferences_/francophones-studies_/current-year_/registration'
import { Route as EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersImport } from './routes/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners'
import { Route as EventsConferencesFrancophonesStudiesCurrentYearInfoImport } from './routes/events_/conferences_/francophones-studies_/current-year_/info'
import { Route as EventsConferencesFrancophonesStudiesCurrentYearCallsImport } from './routes/events_/conferences_/francophones-studies_/current-year_/calls'
import { Route as EventsConferencesCieftPreviousEditionsYearImport } from './routes/events_/conferences_/cieft_/previous-editions_/$year'
import { Route as EventsConferencesCieftCurrentYearScientificCommitteeImport } from './routes/events_/conferences_/cieft_/current-year_/scientific-committee'
import { Route as EventsConferencesCieftCurrentYearRegistrationImport } from './routes/events_/conferences_/cieft_/current-year_/registration'
import { Route as EventsConferencesCieftCurrentYearOrganizersAndPartnersImport } from './routes/events_/conferences_/cieft_/current-year_/organizers-and-partners'
import { Route as EventsConferencesCieftCurrentYearInfoImport } from './routes/events_/conferences_/cieft_/current-year_/info'
import { Route as EventsConferencesCieftCurrentYearCallsImport } from './routes/events_/conferences_/cieft_/current-year_/calls'
import { Route as ResearchPublicationsDialogueFrancophonesCallsPastIndexImport } from './routes/research_/publications_/dialogue-francophones_/calls_/past/index'
import { Route as ResearchPublicationsDialogueFrancophonesCallsFutureIndexImport } from './routes/research_/publications_/dialogue-francophones_/calls_/future/index'
import { Route as ResearchPublicationsAgapesFrancophonesCallsPastIndexImport } from './routes/research_/publications_/agapes-francophones_/calls_/past/index'
import { Route as ResearchPublicationsAgapesFrancophonesCallsFutureIndexImport } from './routes/research_/publications_/agapes-francophones_/calls_/future/index'

// Create/Update Routes

const LoginRouteRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ContactRouteRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutPartnersRouteRoute = AboutPartnersRouteImport.update({
  id: '/about_/partners',
  path: '/about/partners',
  getParentRoute: () => rootRoute,
} as any)

const ResearchProjectsIndexRoute = ResearchProjectsIndexImport.update({
  id: '/research_/projects/',
  path: '/research/projects/',
  getParentRoute: () => rootRoute,
} as any)

const EventsRoundTablesIndexRoute = EventsRoundTablesIndexImport.update({
  id: '/events_/round-tables/',
  path: '/events/round-tables/',
  getParentRoute: () => rootRoute,
} as any)

const EventsPhdThesesIndexRoute = EventsPhdThesesIndexImport.update({
  id: '/events_/phd-theses/',
  path: '/events/phd-theses/',
  getParentRoute: () => rootRoute,
} as any)

const AboutPartnersIndexRoute = AboutPartnersIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutPartnersRouteRoute,
} as any)

const AboutMembersIndexRoute = AboutMembersIndexImport.update({
  id: '/about_/members/',
  path: '/about/members/',
  getParentRoute: () => rootRoute,
} as any)

const AboutHistoryIndexRoute = AboutHistoryIndexImport.update({
  id: '/about_/history/',
  path: '/about/history/',
  getParentRoute: () => rootRoute,
} as any)

const AboutDescriptionAndObjectivesIndexRoute =
  AboutDescriptionAndObjectivesIndexImport.update({
    id: '/about_/description-and-objectives/',
    path: '/about/description-and-objectives/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsTranslationsIndexRoute =
  ResearchPublicationsTranslationsIndexImport.update({
    id: '/research_/publications_/translations/',
    path: '/research/publications/translations/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsMembersPublicationsIndexRoute =
  ResearchPublicationsMembersPublicationsIndexImport.update({
    id: '/research_/publications_/members-publications/',
    path: '/research/publications/members-publications/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsLingvisticConferencesIndexRoute =
  ResearchPublicationsLingvisticConferencesIndexImport.update({
    id: '/research_/publications_/lingvistic-conferences/',
    path: '/research/publications/lingvistic-conferences/',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesLingvisticFrancophonesIndexRoute =
  EventsConferencesLingvisticFrancophonesIndexImport.update({
    id: '/events_/conferences_/lingvistic-francophones/',
    path: '/events/conferences/lingvistic-francophones/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsDialogueFrancophonesVolumesIndexRoute =
  ResearchPublicationsDialogueFrancophonesVolumesIndexImport.update({
    id: '/research_/publications_/dialogue-francophones_/volumes/',
    path: '/research/publications/dialogue-francophones/volumes/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsDialogueFrancophonesIndexingIndexRoute =
  ResearchPublicationsDialogueFrancophonesIndexingIndexImport.update({
    id: '/research_/publications_/dialogue-francophones_/indexing/',
    path: '/research/publications/dialogue-francophones/indexing/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute =
  ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexImport.update({
    id: '/research_/publications_/dialogue-francophones_/editorial-policy/',
    path: '/research/publications/dialogue-francophones/editorial-policy/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute =
  ResearchPublicationsDialogueFrancophonesCommitteesIndexImport.update({
    id: '/research_/publications_/dialogue-francophones_/committees/',
    path: '/research/publications/dialogue-francophones/committees/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsDialogueFrancophonesAboutIndexRoute =
  ResearchPublicationsDialogueFrancophonesAboutIndexImport.update({
    id: '/research_/publications_/dialogue-francophones_/about/',
    path: '/research/publications/dialogue-francophones/about/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsAgapesFrancophonesVolumesIndexRoute =
  ResearchPublicationsAgapesFrancophonesVolumesIndexImport.update({
    id: '/research_/publications_/agapes-francophones_/volumes/',
    path: '/research/publications/agapes-francophones/volumes/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsAgapesFrancophonesIndexingIndexRoute =
  ResearchPublicationsAgapesFrancophonesIndexingIndexImport.update({
    id: '/research_/publications_/agapes-francophones_/indexing/',
    path: '/research/publications/agapes-francophones/indexing/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute =
  ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexImport.update({
    id: '/research_/publications_/agapes-francophones_/editorial-policy/',
    path: '/research/publications/agapes-francophones/editorial-policy/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute =
  ResearchPublicationsAgapesFrancophonesCommitteesIndexImport.update({
    id: '/research_/publications_/agapes-francophones_/committees/',
    path: '/research/publications/agapes-francophones/committees/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsAgapesFrancophonesAboutIndexRoute =
  ResearchPublicationsAgapesFrancophonesAboutIndexImport.update({
    id: '/research_/publications_/agapes-francophones_/about/',
    path: '/research/publications/agapes-francophones/about/',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute =
  EventsConferencesFrancophonesStudiesPreviousEditionsIndexImport.update({
    id: '/events_/conferences_/francophones-studies_/previous-editions_/',
    path: '/events/conferences/francophones-studies/previous-editions/',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesCieftPreviousEditionsIndexRoute =
  EventsConferencesCieftPreviousEditionsIndexImport.update({
    id: '/events_/conferences_/cieft_/previous-editions_/',
    path: '/events/conferences/cieft/previous-editions/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute =
  ResearchPublicationsDialogueFrancophonesVolumesVolumeIdImport.update({
    id: '/research_/publications_/dialogue-francophones_/volumes/$volumeId',
    path: '/research/publications/dialogue-francophones/volumes/$volumeId',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute =
  ResearchPublicationsDialogueFrancophonesRegistrationRegistrationImport.update(
    {
      id: '/research_/publications_/dialogue-francophones_/registration/registration',
      path: '/research/publications/dialogue-francophones/registration/registration',
      getParentRoute: () => rootRoute,
    } as any,
  )

const ResearchPublicationsDialogueFrancophonesCallsCallIdRoute =
  ResearchPublicationsDialogueFrancophonesCallsCallIdImport.update({
    id: '/research_/publications_/dialogue-francophones_/calls_/$callId',
    path: '/research/publications/dialogue-francophones/calls/$callId',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute =
  EventsConferencesFrancophonesStudiesPreviousEditionsYearImport.update({
    id: '/events_/conferences_/francophones-studies_/previous-editions_/$year',
    path: '/events/conferences/francophones-studies/previous-editions/$year',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeRoute =
  EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeImport.update(
    {
      id: '/events_/conferences_/francophones-studies_/current-year_/scientific-committee',
      path: '/events/conferences/francophones-studies/current-year/scientific-committee',
      getParentRoute: () => rootRoute,
    } as any,
  )

const EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute =
  EventsConferencesFrancophonesStudiesCurrentYearRegistrationImport.update({
    id: '/events_/conferences_/francophones-studies_/current-year_/registration',
    path: '/events/conferences/francophones-studies/current-year/registration',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersRoute =
  EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersImport.update(
    {
      id: '/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners',
      path: '/events/conferences/francophones-studies/current-year/organizers-and-partners',
      getParentRoute: () => rootRoute,
    } as any,
  )

const EventsConferencesFrancophonesStudiesCurrentYearInfoRoute =
  EventsConferencesFrancophonesStudiesCurrentYearInfoImport.update({
    id: '/events_/conferences_/francophones-studies_/current-year_/info',
    path: '/events/conferences/francophones-studies/current-year/info',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesFrancophonesStudiesCurrentYearCallsRoute =
  EventsConferencesFrancophonesStudiesCurrentYearCallsImport.update({
    id: '/events_/conferences_/francophones-studies_/current-year_/calls',
    path: '/events/conferences/francophones-studies/current-year/calls',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesCieftPreviousEditionsYearRoute =
  EventsConferencesCieftPreviousEditionsYearImport.update({
    id: '/events_/conferences_/cieft_/previous-editions_/$year',
    path: '/events/conferences/cieft/previous-editions/$year',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesCieftCurrentYearScientificCommitteeRoute =
  EventsConferencesCieftCurrentYearScientificCommitteeImport.update({
    id: '/events_/conferences_/cieft_/current-year_/scientific-committee',
    path: '/events/conferences/cieft/current-year/scientific-committee',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesCieftCurrentYearRegistrationRoute =
  EventsConferencesCieftCurrentYearRegistrationImport.update({
    id: '/events_/conferences_/cieft_/current-year_/registration',
    path: '/events/conferences/cieft/current-year/registration',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesCieftCurrentYearOrganizersAndPartnersRoute =
  EventsConferencesCieftCurrentYearOrganizersAndPartnersImport.update({
    id: '/events_/conferences_/cieft_/current-year_/organizers-and-partners',
    path: '/events/conferences/cieft/current-year/organizers-and-partners',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesCieftCurrentYearInfoRoute =
  EventsConferencesCieftCurrentYearInfoImport.update({
    id: '/events_/conferences_/cieft_/current-year_/info',
    path: '/events/conferences/cieft/current-year/info',
    getParentRoute: () => rootRoute,
  } as any)

const EventsConferencesCieftCurrentYearCallsRoute =
  EventsConferencesCieftCurrentYearCallsImport.update({
    id: '/events_/conferences_/cieft_/current-year_/calls',
    path: '/events/conferences/cieft/current-year/calls',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute =
  ResearchPublicationsDialogueFrancophonesCallsPastIndexImport.update({
    id: '/research_/publications_/dialogue-francophones_/calls_/past/',
    path: '/research/publications/dialogue-francophones/calls/past/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute =
  ResearchPublicationsDialogueFrancophonesCallsFutureIndexImport.update({
    id: '/research_/publications_/dialogue-francophones_/calls_/future/',
    path: '/research/publications/dialogue-francophones/calls/future/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute =
  ResearchPublicationsAgapesFrancophonesCallsPastIndexImport.update({
    id: '/research_/publications_/agapes-francophones_/calls_/past/',
    path: '/research/publications/agapes-francophones/calls/past/',
    getParentRoute: () => rootRoute,
  } as any)

const ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute =
  ResearchPublicationsAgapesFrancophonesCallsFutureIndexImport.update({
    id: '/research_/publications_/agapes-francophones_/calls_/future/',
    path: '/research/publications/agapes-francophones/calls/future/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/about_/partners': {
      id: '/about_/partners'
      path: '/about/partners'
      fullPath: '/about/partners'
      preLoaderRoute: typeof AboutPartnersRouteImport
      parentRoute: typeof rootRoute
    }
    '/about_/description-and-objectives/': {
      id: '/about_/description-and-objectives/'
      path: '/about/description-and-objectives'
      fullPath: '/about/description-and-objectives'
      preLoaderRoute: typeof AboutDescriptionAndObjectivesIndexImport
      parentRoute: typeof rootRoute
    }
    '/about_/history/': {
      id: '/about_/history/'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/about_/members/': {
      id: '/about_/members/'
      path: '/about/members'
      fullPath: '/about/members'
      preLoaderRoute: typeof AboutMembersIndexImport
      parentRoute: typeof rootRoute
    }
    '/about_/partners/': {
      id: '/about_/partners/'
      path: '/'
      fullPath: '/about/partners/'
      preLoaderRoute: typeof AboutPartnersIndexImport
      parentRoute: typeof AboutPartnersRouteImport
    }
    '/events_/phd-theses/': {
      id: '/events_/phd-theses/'
      path: '/events/phd-theses'
      fullPath: '/events/phd-theses'
      preLoaderRoute: typeof EventsPhdThesesIndexImport
      parentRoute: typeof rootRoute
    }
    '/events_/round-tables/': {
      id: '/events_/round-tables/'
      path: '/events/round-tables'
      fullPath: '/events/round-tables'
      preLoaderRoute: typeof EventsRoundTablesIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/projects/': {
      id: '/research_/projects/'
      path: '/research/projects'
      fullPath: '/research/projects'
      preLoaderRoute: typeof ResearchProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/lingvistic-francophones/': {
      id: '/events_/conferences_/lingvistic-francophones/'
      path: '/events/conferences/lingvistic-francophones'
      fullPath: '/events/conferences/lingvistic-francophones'
      preLoaderRoute: typeof EventsConferencesLingvisticFrancophonesIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/lingvistic-conferences/': {
      id: '/research_/publications_/lingvistic-conferences/'
      path: '/research/publications/lingvistic-conferences'
      fullPath: '/research/publications/lingvistic-conferences'
      preLoaderRoute: typeof ResearchPublicationsLingvisticConferencesIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/members-publications/': {
      id: '/research_/publications_/members-publications/'
      path: '/research/publications/members-publications'
      fullPath: '/research/publications/members-publications'
      preLoaderRoute: typeof ResearchPublicationsMembersPublicationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/translations/': {
      id: '/research_/publications_/translations/'
      path: '/research/publications/translations'
      fullPath: '/research/publications/translations'
      preLoaderRoute: typeof ResearchPublicationsTranslationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/cieft_/current-year_/calls': {
      id: '/events_/conferences_/cieft_/current-year_/calls'
      path: '/events/conferences/cieft/current-year/calls'
      fullPath: '/events/conferences/cieft/current-year/calls'
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearCallsImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/cieft_/current-year_/info': {
      id: '/events_/conferences_/cieft_/current-year_/info'
      path: '/events/conferences/cieft/current-year/info'
      fullPath: '/events/conferences/cieft/current-year/info'
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearInfoImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/cieft_/current-year_/organizers-and-partners': {
      id: '/events_/conferences_/cieft_/current-year_/organizers-and-partners'
      path: '/events/conferences/cieft/current-year/organizers-and-partners'
      fullPath: '/events/conferences/cieft/current-year/organizers-and-partners'
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearOrganizersAndPartnersImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/cieft_/current-year_/registration': {
      id: '/events_/conferences_/cieft_/current-year_/registration'
      path: '/events/conferences/cieft/current-year/registration'
      fullPath: '/events/conferences/cieft/current-year/registration'
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearRegistrationImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/cieft_/current-year_/scientific-committee': {
      id: '/events_/conferences_/cieft_/current-year_/scientific-committee'
      path: '/events/conferences/cieft/current-year/scientific-committee'
      fullPath: '/events/conferences/cieft/current-year/scientific-committee'
      preLoaderRoute: typeof EventsConferencesCieftCurrentYearScientificCommitteeImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/cieft_/previous-editions_/$year': {
      id: '/events_/conferences_/cieft_/previous-editions_/$year'
      path: '/events/conferences/cieft/previous-editions/$year'
      fullPath: '/events/conferences/cieft/previous-editions/$year'
      preLoaderRoute: typeof EventsConferencesCieftPreviousEditionsYearImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/francophones-studies_/current-year_/calls': {
      id: '/events_/conferences_/francophones-studies_/current-year_/calls'
      path: '/events/conferences/francophones-studies/current-year/calls'
      fullPath: '/events/conferences/francophones-studies/current-year/calls'
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearCallsImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/francophones-studies_/current-year_/info': {
      id: '/events_/conferences_/francophones-studies_/current-year_/info'
      path: '/events/conferences/francophones-studies/current-year/info'
      fullPath: '/events/conferences/francophones-studies/current-year/info'
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearInfoImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners': {
      id: '/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners'
      path: '/events/conferences/francophones-studies/current-year/organizers-and-partners'
      fullPath: '/events/conferences/francophones-studies/current-year/organizers-and-partners'
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/francophones-studies_/current-year_/registration': {
      id: '/events_/conferences_/francophones-studies_/current-year_/registration'
      path: '/events/conferences/francophones-studies/current-year/registration'
      fullPath: '/events/conferences/francophones-studies/current-year/registration'
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearRegistrationImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/francophones-studies_/current-year_/scientific-committee': {
      id: '/events_/conferences_/francophones-studies_/current-year_/scientific-committee'
      path: '/events/conferences/francophones-studies/current-year/scientific-committee'
      fullPath: '/events/conferences/francophones-studies/current-year/scientific-committee'
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/francophones-studies_/previous-editions_/$year': {
      id: '/events_/conferences_/francophones-studies_/previous-editions_/$year'
      path: '/events/conferences/francophones-studies/previous-editions/$year'
      fullPath: '/events/conferences/francophones-studies/previous-editions/$year'
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesPreviousEditionsYearImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/dialogue-francophones_/calls_/$callId': {
      id: '/research_/publications_/dialogue-francophones_/calls_/$callId'
      path: '/research/publications/dialogue-francophones/calls/$callId'
      fullPath: '/research/publications/dialogue-francophones/calls/$callId'
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesCallsCallIdImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/dialogue-francophones_/registration/registration': {
      id: '/research_/publications_/dialogue-francophones_/registration/registration'
      path: '/research/publications/dialogue-francophones/registration/registration'
      fullPath: '/research/publications/dialogue-francophones/registration/registration'
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesRegistrationRegistrationImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/dialogue-francophones_/volumes/$volumeId': {
      id: '/research_/publications_/dialogue-francophones_/volumes/$volumeId'
      path: '/research/publications/dialogue-francophones/volumes/$volumeId'
      fullPath: '/research/publications/dialogue-francophones/volumes/$volumeId'
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesVolumesVolumeIdImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/cieft_/previous-editions_/': {
      id: '/events_/conferences_/cieft_/previous-editions_/'
      path: '/events/conferences/cieft/previous-editions'
      fullPath: '/events/conferences/cieft/previous-editions'
      preLoaderRoute: typeof EventsConferencesCieftPreviousEditionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/events_/conferences_/francophones-studies_/previous-editions_/': {
      id: '/events_/conferences_/francophones-studies_/previous-editions_/'
      path: '/events/conferences/francophones-studies/previous-editions'
      fullPath: '/events/conferences/francophones-studies/previous-editions'
      preLoaderRoute: typeof EventsConferencesFrancophonesStudiesPreviousEditionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/agapes-francophones_/about/': {
      id: '/research_/publications_/agapes-francophones_/about/'
      path: '/research/publications/agapes-francophones/about'
      fullPath: '/research/publications/agapes-francophones/about'
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesAboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/agapes-francophones_/committees/': {
      id: '/research_/publications_/agapes-francophones_/committees/'
      path: '/research/publications/agapes-francophones/committees'
      fullPath: '/research/publications/agapes-francophones/committees'
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesCommitteesIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/agapes-francophones_/editorial-policy/': {
      id: '/research_/publications_/agapes-francophones_/editorial-policy/'
      path: '/research/publications/agapes-francophones/editorial-policy'
      fullPath: '/research/publications/agapes-francophones/editorial-policy'
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/agapes-francophones_/indexing/': {
      id: '/research_/publications_/agapes-francophones_/indexing/'
      path: '/research/publications/agapes-francophones/indexing'
      fullPath: '/research/publications/agapes-francophones/indexing'
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesIndexingIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/agapes-francophones_/volumes/': {
      id: '/research_/publications_/agapes-francophones_/volumes/'
      path: '/research/publications/agapes-francophones/volumes'
      fullPath: '/research/publications/agapes-francophones/volumes'
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesVolumesIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/dialogue-francophones_/about/': {
      id: '/research_/publications_/dialogue-francophones_/about/'
      path: '/research/publications/dialogue-francophones/about'
      fullPath: '/research/publications/dialogue-francophones/about'
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesAboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/dialogue-francophones_/committees/': {
      id: '/research_/publications_/dialogue-francophones_/committees/'
      path: '/research/publications/dialogue-francophones/committees'
      fullPath: '/research/publications/dialogue-francophones/committees'
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesCommitteesIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/dialogue-francophones_/editorial-policy/': {
      id: '/research_/publications_/dialogue-francophones_/editorial-policy/'
      path: '/research/publications/dialogue-francophones/editorial-policy'
      fullPath: '/research/publications/dialogue-francophones/editorial-policy'
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/dialogue-francophones_/indexing/': {
      id: '/research_/publications_/dialogue-francophones_/indexing/'
      path: '/research/publications/dialogue-francophones/indexing'
      fullPath: '/research/publications/dialogue-francophones/indexing'
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesIndexingIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/dialogue-francophones_/volumes/': {
      id: '/research_/publications_/dialogue-francophones_/volumes/'
      path: '/research/publications/dialogue-francophones/volumes'
      fullPath: '/research/publications/dialogue-francophones/volumes'
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesVolumesIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/agapes-francophones_/calls_/future/': {
      id: '/research_/publications_/agapes-francophones_/calls_/future/'
      path: '/research/publications/agapes-francophones/calls/future'
      fullPath: '/research/publications/agapes-francophones/calls/future'
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesCallsFutureIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/agapes-francophones_/calls_/past/': {
      id: '/research_/publications_/agapes-francophones_/calls_/past/'
      path: '/research/publications/agapes-francophones/calls/past'
      fullPath: '/research/publications/agapes-francophones/calls/past'
      preLoaderRoute: typeof ResearchPublicationsAgapesFrancophonesCallsPastIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/dialogue-francophones_/calls_/future/': {
      id: '/research_/publications_/dialogue-francophones_/calls_/future/'
      path: '/research/publications/dialogue-francophones/calls/future'
      fullPath: '/research/publications/dialogue-francophones/calls/future'
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesCallsFutureIndexImport
      parentRoute: typeof rootRoute
    }
    '/research_/publications_/dialogue-francophones_/calls_/past/': {
      id: '/research_/publications_/dialogue-francophones_/calls_/past/'
      path: '/research/publications/dialogue-francophones/calls/past'
      fullPath: '/research/publications/dialogue-francophones/calls/past'
      preLoaderRoute: typeof ResearchPublicationsDialogueFrancophonesCallsPastIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AboutPartnersRouteRouteChildren {
  AboutPartnersIndexRoute: typeof AboutPartnersIndexRoute
}

const AboutPartnersRouteRouteChildren: AboutPartnersRouteRouteChildren = {
  AboutPartnersIndexRoute: AboutPartnersIndexRoute,
}

const AboutPartnersRouteRouteWithChildren =
  AboutPartnersRouteRoute._addFileChildren(AboutPartnersRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/contact': typeof ContactRouteRoute
  '/login': typeof LoginRouteRoute
  '/about/partners': typeof AboutPartnersRouteRouteWithChildren
  '/about/description-and-objectives': typeof AboutDescriptionAndObjectivesIndexRoute
  '/about/history': typeof AboutHistoryIndexRoute
  '/about/members': typeof AboutMembersIndexRoute
  '/about/partners/': typeof AboutPartnersIndexRoute
  '/events/phd-theses': typeof EventsPhdThesesIndexRoute
  '/events/round-tables': typeof EventsRoundTablesIndexRoute
  '/research/projects': typeof ResearchProjectsIndexRoute
  '/events/conferences/lingvistic-francophones': typeof EventsConferencesLingvisticFrancophonesIndexRoute
  '/research/publications/lingvistic-conferences': typeof ResearchPublicationsLingvisticConferencesIndexRoute
  '/research/publications/members-publications': typeof ResearchPublicationsMembersPublicationsIndexRoute
  '/research/publications/translations': typeof ResearchPublicationsTranslationsIndexRoute
  '/events/conferences/cieft/current-year/calls': typeof EventsConferencesCieftCurrentYearCallsRoute
  '/events/conferences/cieft/current-year/info': typeof EventsConferencesCieftCurrentYearInfoRoute
  '/events/conferences/cieft/current-year/organizers-and-partners': typeof EventsConferencesCieftCurrentYearOrganizersAndPartnersRoute
  '/events/conferences/cieft/current-year/registration': typeof EventsConferencesCieftCurrentYearRegistrationRoute
  '/events/conferences/cieft/current-year/scientific-committee': typeof EventsConferencesCieftCurrentYearScientificCommitteeRoute
  '/events/conferences/cieft/previous-editions/$year': typeof EventsConferencesCieftPreviousEditionsYearRoute
  '/events/conferences/francophones-studies/current-year/calls': typeof EventsConferencesFrancophonesStudiesCurrentYearCallsRoute
  '/events/conferences/francophones-studies/current-year/info': typeof EventsConferencesFrancophonesStudiesCurrentYearInfoRoute
  '/events/conferences/francophones-studies/current-year/organizers-and-partners': typeof EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersRoute
  '/events/conferences/francophones-studies/current-year/registration': typeof EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute
  '/events/conferences/francophones-studies/current-year/scientific-committee': typeof EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeRoute
  '/events/conferences/francophones-studies/previous-editions/$year': typeof EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute
  '/research/publications/dialogue-francophones/calls/$callId': typeof ResearchPublicationsDialogueFrancophonesCallsCallIdRoute
  '/research/publications/dialogue-francophones/registration/registration': typeof ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute
  '/research/publications/dialogue-francophones/volumes/$volumeId': typeof ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute
  '/events/conferences/cieft/previous-editions': typeof EventsConferencesCieftPreviousEditionsIndexRoute
  '/events/conferences/francophones-studies/previous-editions': typeof EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute
  '/research/publications/agapes-francophones/about': typeof ResearchPublicationsAgapesFrancophonesAboutIndexRoute
  '/research/publications/agapes-francophones/committees': typeof ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute
  '/research/publications/agapes-francophones/editorial-policy': typeof ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute
  '/research/publications/agapes-francophones/indexing': typeof ResearchPublicationsAgapesFrancophonesIndexingIndexRoute
  '/research/publications/agapes-francophones/volumes': typeof ResearchPublicationsAgapesFrancophonesVolumesIndexRoute
  '/research/publications/dialogue-francophones/about': typeof ResearchPublicationsDialogueFrancophonesAboutIndexRoute
  '/research/publications/dialogue-francophones/committees': typeof ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute
  '/research/publications/dialogue-francophones/editorial-policy': typeof ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute
  '/research/publications/dialogue-francophones/indexing': typeof ResearchPublicationsDialogueFrancophonesIndexingIndexRoute
  '/research/publications/dialogue-francophones/volumes': typeof ResearchPublicationsDialogueFrancophonesVolumesIndexRoute
  '/research/publications/agapes-francophones/calls/future': typeof ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute
  '/research/publications/agapes-francophones/calls/past': typeof ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute
  '/research/publications/dialogue-francophones/calls/future': typeof ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute
  '/research/publications/dialogue-francophones/calls/past': typeof ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/contact': typeof ContactRouteRoute
  '/login': typeof LoginRouteRoute
  '/about/description-and-objectives': typeof AboutDescriptionAndObjectivesIndexRoute
  '/about/history': typeof AboutHistoryIndexRoute
  '/about/members': typeof AboutMembersIndexRoute
  '/about/partners': typeof AboutPartnersIndexRoute
  '/events/phd-theses': typeof EventsPhdThesesIndexRoute
  '/events/round-tables': typeof EventsRoundTablesIndexRoute
  '/research/projects': typeof ResearchProjectsIndexRoute
  '/events/conferences/lingvistic-francophones': typeof EventsConferencesLingvisticFrancophonesIndexRoute
  '/research/publications/lingvistic-conferences': typeof ResearchPublicationsLingvisticConferencesIndexRoute
  '/research/publications/members-publications': typeof ResearchPublicationsMembersPublicationsIndexRoute
  '/research/publications/translations': typeof ResearchPublicationsTranslationsIndexRoute
  '/events/conferences/cieft/current-year/calls': typeof EventsConferencesCieftCurrentYearCallsRoute
  '/events/conferences/cieft/current-year/info': typeof EventsConferencesCieftCurrentYearInfoRoute
  '/events/conferences/cieft/current-year/organizers-and-partners': typeof EventsConferencesCieftCurrentYearOrganizersAndPartnersRoute
  '/events/conferences/cieft/current-year/registration': typeof EventsConferencesCieftCurrentYearRegistrationRoute
  '/events/conferences/cieft/current-year/scientific-committee': typeof EventsConferencesCieftCurrentYearScientificCommitteeRoute
  '/events/conferences/cieft/previous-editions/$year': typeof EventsConferencesCieftPreviousEditionsYearRoute
  '/events/conferences/francophones-studies/current-year/calls': typeof EventsConferencesFrancophonesStudiesCurrentYearCallsRoute
  '/events/conferences/francophones-studies/current-year/info': typeof EventsConferencesFrancophonesStudiesCurrentYearInfoRoute
  '/events/conferences/francophones-studies/current-year/organizers-and-partners': typeof EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersRoute
  '/events/conferences/francophones-studies/current-year/registration': typeof EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute
  '/events/conferences/francophones-studies/current-year/scientific-committee': typeof EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeRoute
  '/events/conferences/francophones-studies/previous-editions/$year': typeof EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute
  '/research/publications/dialogue-francophones/calls/$callId': typeof ResearchPublicationsDialogueFrancophonesCallsCallIdRoute
  '/research/publications/dialogue-francophones/registration/registration': typeof ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute
  '/research/publications/dialogue-francophones/volumes/$volumeId': typeof ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute
  '/events/conferences/cieft/previous-editions': typeof EventsConferencesCieftPreviousEditionsIndexRoute
  '/events/conferences/francophones-studies/previous-editions': typeof EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute
  '/research/publications/agapes-francophones/about': typeof ResearchPublicationsAgapesFrancophonesAboutIndexRoute
  '/research/publications/agapes-francophones/committees': typeof ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute
  '/research/publications/agapes-francophones/editorial-policy': typeof ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute
  '/research/publications/agapes-francophones/indexing': typeof ResearchPublicationsAgapesFrancophonesIndexingIndexRoute
  '/research/publications/agapes-francophones/volumes': typeof ResearchPublicationsAgapesFrancophonesVolumesIndexRoute
  '/research/publications/dialogue-francophones/about': typeof ResearchPublicationsDialogueFrancophonesAboutIndexRoute
  '/research/publications/dialogue-francophones/committees': typeof ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute
  '/research/publications/dialogue-francophones/editorial-policy': typeof ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute
  '/research/publications/dialogue-francophones/indexing': typeof ResearchPublicationsDialogueFrancophonesIndexingIndexRoute
  '/research/publications/dialogue-francophones/volumes': typeof ResearchPublicationsDialogueFrancophonesVolumesIndexRoute
  '/research/publications/agapes-francophones/calls/future': typeof ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute
  '/research/publications/agapes-francophones/calls/past': typeof ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute
  '/research/publications/dialogue-francophones/calls/future': typeof ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute
  '/research/publications/dialogue-francophones/calls/past': typeof ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRouteRoute
  '/contact': typeof ContactRouteRoute
  '/login': typeof LoginRouteRoute
  '/about_/partners': typeof AboutPartnersRouteRouteWithChildren
  '/about_/description-and-objectives/': typeof AboutDescriptionAndObjectivesIndexRoute
  '/about_/history/': typeof AboutHistoryIndexRoute
  '/about_/members/': typeof AboutMembersIndexRoute
  '/about_/partners/': typeof AboutPartnersIndexRoute
  '/events_/phd-theses/': typeof EventsPhdThesesIndexRoute
  '/events_/round-tables/': typeof EventsRoundTablesIndexRoute
  '/research_/projects/': typeof ResearchProjectsIndexRoute
  '/events_/conferences_/lingvistic-francophones/': typeof EventsConferencesLingvisticFrancophonesIndexRoute
  '/research_/publications_/lingvistic-conferences/': typeof ResearchPublicationsLingvisticConferencesIndexRoute
  '/research_/publications_/members-publications/': typeof ResearchPublicationsMembersPublicationsIndexRoute
  '/research_/publications_/translations/': typeof ResearchPublicationsTranslationsIndexRoute
  '/events_/conferences_/cieft_/current-year_/calls': typeof EventsConferencesCieftCurrentYearCallsRoute
  '/events_/conferences_/cieft_/current-year_/info': typeof EventsConferencesCieftCurrentYearInfoRoute
  '/events_/conferences_/cieft_/current-year_/organizers-and-partners': typeof EventsConferencesCieftCurrentYearOrganizersAndPartnersRoute
  '/events_/conferences_/cieft_/current-year_/registration': typeof EventsConferencesCieftCurrentYearRegistrationRoute
  '/events_/conferences_/cieft_/current-year_/scientific-committee': typeof EventsConferencesCieftCurrentYearScientificCommitteeRoute
  '/events_/conferences_/cieft_/previous-editions_/$year': typeof EventsConferencesCieftPreviousEditionsYearRoute
  '/events_/conferences_/francophones-studies_/current-year_/calls': typeof EventsConferencesFrancophonesStudiesCurrentYearCallsRoute
  '/events_/conferences_/francophones-studies_/current-year_/info': typeof EventsConferencesFrancophonesStudiesCurrentYearInfoRoute
  '/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners': typeof EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersRoute
  '/events_/conferences_/francophones-studies_/current-year_/registration': typeof EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute
  '/events_/conferences_/francophones-studies_/current-year_/scientific-committee': typeof EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeRoute
  '/events_/conferences_/francophones-studies_/previous-editions_/$year': typeof EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute
  '/research_/publications_/dialogue-francophones_/calls_/$callId': typeof ResearchPublicationsDialogueFrancophonesCallsCallIdRoute
  '/research_/publications_/dialogue-francophones_/registration/registration': typeof ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute
  '/research_/publications_/dialogue-francophones_/volumes/$volumeId': typeof ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute
  '/events_/conferences_/cieft_/previous-editions_/': typeof EventsConferencesCieftPreviousEditionsIndexRoute
  '/events_/conferences_/francophones-studies_/previous-editions_/': typeof EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute
  '/research_/publications_/agapes-francophones_/about/': typeof ResearchPublicationsAgapesFrancophonesAboutIndexRoute
  '/research_/publications_/agapes-francophones_/committees/': typeof ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute
  '/research_/publications_/agapes-francophones_/editorial-policy/': typeof ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute
  '/research_/publications_/agapes-francophones_/indexing/': typeof ResearchPublicationsAgapesFrancophonesIndexingIndexRoute
  '/research_/publications_/agapes-francophones_/volumes/': typeof ResearchPublicationsAgapesFrancophonesVolumesIndexRoute
  '/research_/publications_/dialogue-francophones_/about/': typeof ResearchPublicationsDialogueFrancophonesAboutIndexRoute
  '/research_/publications_/dialogue-francophones_/committees/': typeof ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute
  '/research_/publications_/dialogue-francophones_/editorial-policy/': typeof ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute
  '/research_/publications_/dialogue-francophones_/indexing/': typeof ResearchPublicationsDialogueFrancophonesIndexingIndexRoute
  '/research_/publications_/dialogue-francophones_/volumes/': typeof ResearchPublicationsDialogueFrancophonesVolumesIndexRoute
  '/research_/publications_/agapes-francophones_/calls_/future/': typeof ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute
  '/research_/publications_/agapes-francophones_/calls_/past/': typeof ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute
  '/research_/publications_/dialogue-francophones_/calls_/future/': typeof ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute
  '/research_/publications_/dialogue-francophones_/calls_/past/': typeof ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/about/partners'
    | '/about/description-and-objectives'
    | '/about/history'
    | '/about/members'
    | '/about/partners/'
    | '/events/phd-theses'
    | '/events/round-tables'
    | '/research/projects'
    | '/events/conferences/lingvistic-francophones'
    | '/research/publications/lingvistic-conferences'
    | '/research/publications/members-publications'
    | '/research/publications/translations'
    | '/events/conferences/cieft/current-year/calls'
    | '/events/conferences/cieft/current-year/info'
    | '/events/conferences/cieft/current-year/organizers-and-partners'
    | '/events/conferences/cieft/current-year/registration'
    | '/events/conferences/cieft/current-year/scientific-committee'
    | '/events/conferences/cieft/previous-editions/$year'
    | '/events/conferences/francophones-studies/current-year/calls'
    | '/events/conferences/francophones-studies/current-year/info'
    | '/events/conferences/francophones-studies/current-year/organizers-and-partners'
    | '/events/conferences/francophones-studies/current-year/registration'
    | '/events/conferences/francophones-studies/current-year/scientific-committee'
    | '/events/conferences/francophones-studies/previous-editions/$year'
    | '/research/publications/dialogue-francophones/calls/$callId'
    | '/research/publications/dialogue-francophones/registration/registration'
    | '/research/publications/dialogue-francophones/volumes/$volumeId'
    | '/events/conferences/cieft/previous-editions'
    | '/events/conferences/francophones-studies/previous-editions'
    | '/research/publications/agapes-francophones/about'
    | '/research/publications/agapes-francophones/committees'
    | '/research/publications/agapes-francophones/editorial-policy'
    | '/research/publications/agapes-francophones/indexing'
    | '/research/publications/agapes-francophones/volumes'
    | '/research/publications/dialogue-francophones/about'
    | '/research/publications/dialogue-francophones/committees'
    | '/research/publications/dialogue-francophones/editorial-policy'
    | '/research/publications/dialogue-francophones/indexing'
    | '/research/publications/dialogue-francophones/volumes'
    | '/research/publications/agapes-francophones/calls/future'
    | '/research/publications/agapes-francophones/calls/past'
    | '/research/publications/dialogue-francophones/calls/future'
    | '/research/publications/dialogue-francophones/calls/past'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/about/description-and-objectives'
    | '/about/history'
    | '/about/members'
    | '/about/partners'
    | '/events/phd-theses'
    | '/events/round-tables'
    | '/research/projects'
    | '/events/conferences/lingvistic-francophones'
    | '/research/publications/lingvistic-conferences'
    | '/research/publications/members-publications'
    | '/research/publications/translations'
    | '/events/conferences/cieft/current-year/calls'
    | '/events/conferences/cieft/current-year/info'
    | '/events/conferences/cieft/current-year/organizers-and-partners'
    | '/events/conferences/cieft/current-year/registration'
    | '/events/conferences/cieft/current-year/scientific-committee'
    | '/events/conferences/cieft/previous-editions/$year'
    | '/events/conferences/francophones-studies/current-year/calls'
    | '/events/conferences/francophones-studies/current-year/info'
    | '/events/conferences/francophones-studies/current-year/organizers-and-partners'
    | '/events/conferences/francophones-studies/current-year/registration'
    | '/events/conferences/francophones-studies/current-year/scientific-committee'
    | '/events/conferences/francophones-studies/previous-editions/$year'
    | '/research/publications/dialogue-francophones/calls/$callId'
    | '/research/publications/dialogue-francophones/registration/registration'
    | '/research/publications/dialogue-francophones/volumes/$volumeId'
    | '/events/conferences/cieft/previous-editions'
    | '/events/conferences/francophones-studies/previous-editions'
    | '/research/publications/agapes-francophones/about'
    | '/research/publications/agapes-francophones/committees'
    | '/research/publications/agapes-francophones/editorial-policy'
    | '/research/publications/agapes-francophones/indexing'
    | '/research/publications/agapes-francophones/volumes'
    | '/research/publications/dialogue-francophones/about'
    | '/research/publications/dialogue-francophones/committees'
    | '/research/publications/dialogue-francophones/editorial-policy'
    | '/research/publications/dialogue-francophones/indexing'
    | '/research/publications/dialogue-francophones/volumes'
    | '/research/publications/agapes-francophones/calls/future'
    | '/research/publications/agapes-francophones/calls/past'
    | '/research/publications/dialogue-francophones/calls/future'
    | '/research/publications/dialogue-francophones/calls/past'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/login'
    | '/about_/partners'
    | '/about_/description-and-objectives/'
    | '/about_/history/'
    | '/about_/members/'
    | '/about_/partners/'
    | '/events_/phd-theses/'
    | '/events_/round-tables/'
    | '/research_/projects/'
    | '/events_/conferences_/lingvistic-francophones/'
    | '/research_/publications_/lingvistic-conferences/'
    | '/research_/publications_/members-publications/'
    | '/research_/publications_/translations/'
    | '/events_/conferences_/cieft_/current-year_/calls'
    | '/events_/conferences_/cieft_/current-year_/info'
    | '/events_/conferences_/cieft_/current-year_/organizers-and-partners'
    | '/events_/conferences_/cieft_/current-year_/registration'
    | '/events_/conferences_/cieft_/current-year_/scientific-committee'
    | '/events_/conferences_/cieft_/previous-editions_/$year'
    | '/events_/conferences_/francophones-studies_/current-year_/calls'
    | '/events_/conferences_/francophones-studies_/current-year_/info'
    | '/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners'
    | '/events_/conferences_/francophones-studies_/current-year_/registration'
    | '/events_/conferences_/francophones-studies_/current-year_/scientific-committee'
    | '/events_/conferences_/francophones-studies_/previous-editions_/$year'
    | '/research_/publications_/dialogue-francophones_/calls_/$callId'
    | '/research_/publications_/dialogue-francophones_/registration/registration'
    | '/research_/publications_/dialogue-francophones_/volumes/$volumeId'
    | '/events_/conferences_/cieft_/previous-editions_/'
    | '/events_/conferences_/francophones-studies_/previous-editions_/'
    | '/research_/publications_/agapes-francophones_/about/'
    | '/research_/publications_/agapes-francophones_/committees/'
    | '/research_/publications_/agapes-francophones_/editorial-policy/'
    | '/research_/publications_/agapes-francophones_/indexing/'
    | '/research_/publications_/agapes-francophones_/volumes/'
    | '/research_/publications_/dialogue-francophones_/about/'
    | '/research_/publications_/dialogue-francophones_/committees/'
    | '/research_/publications_/dialogue-francophones_/editorial-policy/'
    | '/research_/publications_/dialogue-francophones_/indexing/'
    | '/research_/publications_/dialogue-francophones_/volumes/'
    | '/research_/publications_/agapes-francophones_/calls_/future/'
    | '/research_/publications_/agapes-francophones_/calls_/past/'
    | '/research_/publications_/dialogue-francophones_/calls_/future/'
    | '/research_/publications_/dialogue-francophones_/calls_/past/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  ContactRouteRoute: typeof ContactRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  AboutPartnersRouteRoute: typeof AboutPartnersRouteRouteWithChildren
  AboutDescriptionAndObjectivesIndexRoute: typeof AboutDescriptionAndObjectivesIndexRoute
  AboutHistoryIndexRoute: typeof AboutHistoryIndexRoute
  AboutMembersIndexRoute: typeof AboutMembersIndexRoute
  EventsPhdThesesIndexRoute: typeof EventsPhdThesesIndexRoute
  EventsRoundTablesIndexRoute: typeof EventsRoundTablesIndexRoute
  ResearchProjectsIndexRoute: typeof ResearchProjectsIndexRoute
  EventsConferencesLingvisticFrancophonesIndexRoute: typeof EventsConferencesLingvisticFrancophonesIndexRoute
  ResearchPublicationsLingvisticConferencesIndexRoute: typeof ResearchPublicationsLingvisticConferencesIndexRoute
  ResearchPublicationsMembersPublicationsIndexRoute: typeof ResearchPublicationsMembersPublicationsIndexRoute
  ResearchPublicationsTranslationsIndexRoute: typeof ResearchPublicationsTranslationsIndexRoute
  EventsConferencesCieftCurrentYearCallsRoute: typeof EventsConferencesCieftCurrentYearCallsRoute
  EventsConferencesCieftCurrentYearInfoRoute: typeof EventsConferencesCieftCurrentYearInfoRoute
  EventsConferencesCieftCurrentYearOrganizersAndPartnersRoute: typeof EventsConferencesCieftCurrentYearOrganizersAndPartnersRoute
  EventsConferencesCieftCurrentYearRegistrationRoute: typeof EventsConferencesCieftCurrentYearRegistrationRoute
  EventsConferencesCieftCurrentYearScientificCommitteeRoute: typeof EventsConferencesCieftCurrentYearScientificCommitteeRoute
  EventsConferencesCieftPreviousEditionsYearRoute: typeof EventsConferencesCieftPreviousEditionsYearRoute
  EventsConferencesFrancophonesStudiesCurrentYearCallsRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearCallsRoute
  EventsConferencesFrancophonesStudiesCurrentYearInfoRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearInfoRoute
  EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersRoute
  EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute
  EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeRoute: typeof EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeRoute
  EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute: typeof EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute
  ResearchPublicationsDialogueFrancophonesCallsCallIdRoute: typeof ResearchPublicationsDialogueFrancophonesCallsCallIdRoute
  ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute: typeof ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute
  ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute: typeof ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute
  EventsConferencesCieftPreviousEditionsIndexRoute: typeof EventsConferencesCieftPreviousEditionsIndexRoute
  EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute: typeof EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute
  ResearchPublicationsAgapesFrancophonesAboutIndexRoute: typeof ResearchPublicationsAgapesFrancophonesAboutIndexRoute
  ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute: typeof ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute
  ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute: typeof ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute
  ResearchPublicationsAgapesFrancophonesIndexingIndexRoute: typeof ResearchPublicationsAgapesFrancophonesIndexingIndexRoute
  ResearchPublicationsAgapesFrancophonesVolumesIndexRoute: typeof ResearchPublicationsAgapesFrancophonesVolumesIndexRoute
  ResearchPublicationsDialogueFrancophonesAboutIndexRoute: typeof ResearchPublicationsDialogueFrancophonesAboutIndexRoute
  ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute: typeof ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute
  ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute: typeof ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute
  ResearchPublicationsDialogueFrancophonesIndexingIndexRoute: typeof ResearchPublicationsDialogueFrancophonesIndexingIndexRoute
  ResearchPublicationsDialogueFrancophonesVolumesIndexRoute: typeof ResearchPublicationsDialogueFrancophonesVolumesIndexRoute
  ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute: typeof ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute
  ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute: typeof ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute
  ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute: typeof ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute
  ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute: typeof ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  ContactRouteRoute: ContactRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  AboutPartnersRouteRoute: AboutPartnersRouteRouteWithChildren,
  AboutDescriptionAndObjectivesIndexRoute:
    AboutDescriptionAndObjectivesIndexRoute,
  AboutHistoryIndexRoute: AboutHistoryIndexRoute,
  AboutMembersIndexRoute: AboutMembersIndexRoute,
  EventsPhdThesesIndexRoute: EventsPhdThesesIndexRoute,
  EventsRoundTablesIndexRoute: EventsRoundTablesIndexRoute,
  ResearchProjectsIndexRoute: ResearchProjectsIndexRoute,
  EventsConferencesLingvisticFrancophonesIndexRoute:
    EventsConferencesLingvisticFrancophonesIndexRoute,
  ResearchPublicationsLingvisticConferencesIndexRoute:
    ResearchPublicationsLingvisticConferencesIndexRoute,
  ResearchPublicationsMembersPublicationsIndexRoute:
    ResearchPublicationsMembersPublicationsIndexRoute,
  ResearchPublicationsTranslationsIndexRoute:
    ResearchPublicationsTranslationsIndexRoute,
  EventsConferencesCieftCurrentYearCallsRoute:
    EventsConferencesCieftCurrentYearCallsRoute,
  EventsConferencesCieftCurrentYearInfoRoute:
    EventsConferencesCieftCurrentYearInfoRoute,
  EventsConferencesCieftCurrentYearOrganizersAndPartnersRoute:
    EventsConferencesCieftCurrentYearOrganizersAndPartnersRoute,
  EventsConferencesCieftCurrentYearRegistrationRoute:
    EventsConferencesCieftCurrentYearRegistrationRoute,
  EventsConferencesCieftCurrentYearScientificCommitteeRoute:
    EventsConferencesCieftCurrentYearScientificCommitteeRoute,
  EventsConferencesCieftPreviousEditionsYearRoute:
    EventsConferencesCieftPreviousEditionsYearRoute,
  EventsConferencesFrancophonesStudiesCurrentYearCallsRoute:
    EventsConferencesFrancophonesStudiesCurrentYearCallsRoute,
  EventsConferencesFrancophonesStudiesCurrentYearInfoRoute:
    EventsConferencesFrancophonesStudiesCurrentYearInfoRoute,
  EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersRoute:
    EventsConferencesFrancophonesStudiesCurrentYearOrganizersAndPartnersRoute,
  EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute:
    EventsConferencesFrancophonesStudiesCurrentYearRegistrationRoute,
  EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeRoute:
    EventsConferencesFrancophonesStudiesCurrentYearScientificCommitteeRoute,
  EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute:
    EventsConferencesFrancophonesStudiesPreviousEditionsYearRoute,
  ResearchPublicationsDialogueFrancophonesCallsCallIdRoute:
    ResearchPublicationsDialogueFrancophonesCallsCallIdRoute,
  ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute:
    ResearchPublicationsDialogueFrancophonesRegistrationRegistrationRoute,
  ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute:
    ResearchPublicationsDialogueFrancophonesVolumesVolumeIdRoute,
  EventsConferencesCieftPreviousEditionsIndexRoute:
    EventsConferencesCieftPreviousEditionsIndexRoute,
  EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute:
    EventsConferencesFrancophonesStudiesPreviousEditionsIndexRoute,
  ResearchPublicationsAgapesFrancophonesAboutIndexRoute:
    ResearchPublicationsAgapesFrancophonesAboutIndexRoute,
  ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute:
    ResearchPublicationsAgapesFrancophonesCommitteesIndexRoute,
  ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute:
    ResearchPublicationsAgapesFrancophonesEditorialPolicyIndexRoute,
  ResearchPublicationsAgapesFrancophonesIndexingIndexRoute:
    ResearchPublicationsAgapesFrancophonesIndexingIndexRoute,
  ResearchPublicationsAgapesFrancophonesVolumesIndexRoute:
    ResearchPublicationsAgapesFrancophonesVolumesIndexRoute,
  ResearchPublicationsDialogueFrancophonesAboutIndexRoute:
    ResearchPublicationsDialogueFrancophonesAboutIndexRoute,
  ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute:
    ResearchPublicationsDialogueFrancophonesCommitteesIndexRoute,
  ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute:
    ResearchPublicationsDialogueFrancophonesEditorialPolicyIndexRoute,
  ResearchPublicationsDialogueFrancophonesIndexingIndexRoute:
    ResearchPublicationsDialogueFrancophonesIndexingIndexRoute,
  ResearchPublicationsDialogueFrancophonesVolumesIndexRoute:
    ResearchPublicationsDialogueFrancophonesVolumesIndexRoute,
  ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute:
    ResearchPublicationsAgapesFrancophonesCallsFutureIndexRoute,
  ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute:
    ResearchPublicationsAgapesFrancophonesCallsPastIndexRoute,
  ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute:
    ResearchPublicationsDialogueFrancophonesCallsFutureIndexRoute,
  ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute:
    ResearchPublicationsDialogueFrancophonesCallsPastIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact",
        "/login",
        "/about_/partners",
        "/about_/description-and-objectives/",
        "/about_/history/",
        "/about_/members/",
        "/events_/phd-theses/",
        "/events_/round-tables/",
        "/research_/projects/",
        "/events_/conferences_/lingvistic-francophones/",
        "/research_/publications_/lingvistic-conferences/",
        "/research_/publications_/members-publications/",
        "/research_/publications_/translations/",
        "/events_/conferences_/cieft_/current-year_/calls",
        "/events_/conferences_/cieft_/current-year_/info",
        "/events_/conferences_/cieft_/current-year_/organizers-and-partners",
        "/events_/conferences_/cieft_/current-year_/registration",
        "/events_/conferences_/cieft_/current-year_/scientific-committee",
        "/events_/conferences_/cieft_/previous-editions_/$year",
        "/events_/conferences_/francophones-studies_/current-year_/calls",
        "/events_/conferences_/francophones-studies_/current-year_/info",
        "/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners",
        "/events_/conferences_/francophones-studies_/current-year_/registration",
        "/events_/conferences_/francophones-studies_/current-year_/scientific-committee",
        "/events_/conferences_/francophones-studies_/previous-editions_/$year",
        "/research_/publications_/dialogue-francophones_/calls_/$callId",
        "/research_/publications_/dialogue-francophones_/registration/registration",
        "/research_/publications_/dialogue-francophones_/volumes/$volumeId",
        "/events_/conferences_/cieft_/previous-editions_/",
        "/events_/conferences_/francophones-studies_/previous-editions_/",
        "/research_/publications_/agapes-francophones_/about/",
        "/research_/publications_/agapes-francophones_/committees/",
        "/research_/publications_/agapes-francophones_/editorial-policy/",
        "/research_/publications_/agapes-francophones_/indexing/",
        "/research_/publications_/agapes-francophones_/volumes/",
        "/research_/publications_/dialogue-francophones_/about/",
        "/research_/publications_/dialogue-francophones_/committees/",
        "/research_/publications_/dialogue-francophones_/editorial-policy/",
        "/research_/publications_/dialogue-francophones_/indexing/",
        "/research_/publications_/dialogue-francophones_/volumes/",
        "/research_/publications_/agapes-francophones_/calls_/future/",
        "/research_/publications_/agapes-francophones_/calls_/past/",
        "/research_/publications_/dialogue-francophones_/calls_/future/",
        "/research_/publications_/dialogue-francophones_/calls_/past/"
      ]
    },
    "/": {
      "filePath": "index/route.tsx"
    },
    "/contact": {
      "filePath": "contact/route.tsx"
    },
    "/login": {
      "filePath": "login/route.tsx"
    },
    "/about_/partners": {
      "filePath": "about_/partners/route.tsx",
      "children": [
        "/about_/partners/"
      ]
    },
    "/about_/description-and-objectives/": {
      "filePath": "about_/description-and-objectives/index.tsx"
    },
    "/about_/history/": {
      "filePath": "about_/history/index.tsx"
    },
    "/about_/members/": {
      "filePath": "about_/members/index.tsx"
    },
    "/about_/partners/": {
      "filePath": "about_/partners/index.tsx",
      "parent": "/about_/partners"
    },
    "/events_/phd-theses/": {
      "filePath": "events_/phd-theses/index.tsx"
    },
    "/events_/round-tables/": {
      "filePath": "events_/round-tables/index.tsx"
    },
    "/research_/projects/": {
      "filePath": "research_/projects/index.tsx"
    },
    "/events_/conferences_/lingvistic-francophones/": {
      "filePath": "events_/conferences_/lingvistic-francophones/index.tsx"
    },
    "/research_/publications_/lingvistic-conferences/": {
      "filePath": "research_/publications_/lingvistic-conferences/index.tsx"
    },
    "/research_/publications_/members-publications/": {
      "filePath": "research_/publications_/members-publications/index.tsx"
    },
    "/research_/publications_/translations/": {
      "filePath": "research_/publications_/translations/index.tsx"
    },
    "/events_/conferences_/cieft_/current-year_/calls": {
      "filePath": "events_/conferences_/cieft_/current-year_/calls.tsx"
    },
    "/events_/conferences_/cieft_/current-year_/info": {
      "filePath": "events_/conferences_/cieft_/current-year_/info.tsx"
    },
    "/events_/conferences_/cieft_/current-year_/organizers-and-partners": {
      "filePath": "events_/conferences_/cieft_/current-year_/organizers-and-partners.tsx"
    },
    "/events_/conferences_/cieft_/current-year_/registration": {
      "filePath": "events_/conferences_/cieft_/current-year_/registration.tsx"
    },
    "/events_/conferences_/cieft_/current-year_/scientific-committee": {
      "filePath": "events_/conferences_/cieft_/current-year_/scientific-committee.tsx"
    },
    "/events_/conferences_/cieft_/previous-editions_/$year": {
      "filePath": "events_/conferences_/cieft_/previous-editions_/$year.tsx"
    },
    "/events_/conferences_/francophones-studies_/current-year_/calls": {
      "filePath": "events_/conferences_/francophones-studies_/current-year_/calls.tsx"
    },
    "/events_/conferences_/francophones-studies_/current-year_/info": {
      "filePath": "events_/conferences_/francophones-studies_/current-year_/info.tsx"
    },
    "/events_/conferences_/francophones-studies_/current-year_/organizers-and-partners": {
      "filePath": "events_/conferences_/francophones-studies_/current-year_/organizers-and-partners.tsx"
    },
    "/events_/conferences_/francophones-studies_/current-year_/registration": {
      "filePath": "events_/conferences_/francophones-studies_/current-year_/registration.tsx"
    },
    "/events_/conferences_/francophones-studies_/current-year_/scientific-committee": {
      "filePath": "events_/conferences_/francophones-studies_/current-year_/scientific-committee.tsx"
    },
    "/events_/conferences_/francophones-studies_/previous-editions_/$year": {
      "filePath": "events_/conferences_/francophones-studies_/previous-editions_/$year.tsx"
    },
    "/research_/publications_/dialogue-francophones_/calls_/$callId": {
      "filePath": "research_/publications_/dialogue-francophones_/calls_/$callId.tsx"
    },
    "/research_/publications_/dialogue-francophones_/registration/registration": {
      "filePath": "research_/publications_/dialogue-francophones_/registration/registration.tsx"
    },
    "/research_/publications_/dialogue-francophones_/volumes/$volumeId": {
      "filePath": "research_/publications_/dialogue-francophones_/volumes/$volumeId.tsx"
    },
    "/events_/conferences_/cieft_/previous-editions_/": {
      "filePath": "events_/conferences_/cieft_/previous-editions_/index.tsx"
    },
    "/events_/conferences_/francophones-studies_/previous-editions_/": {
      "filePath": "events_/conferences_/francophones-studies_/previous-editions_/index.tsx"
    },
    "/research_/publications_/agapes-francophones_/about/": {
      "filePath": "research_/publications_/agapes-francophones_/about/index.tsx"
    },
    "/research_/publications_/agapes-francophones_/committees/": {
      "filePath": "research_/publications_/agapes-francophones_/committees/index.tsx"
    },
    "/research_/publications_/agapes-francophones_/editorial-policy/": {
      "filePath": "research_/publications_/agapes-francophones_/editorial-policy/index.tsx"
    },
    "/research_/publications_/agapes-francophones_/indexing/": {
      "filePath": "research_/publications_/agapes-francophones_/indexing/index.tsx"
    },
    "/research_/publications_/agapes-francophones_/volumes/": {
      "filePath": "research_/publications_/agapes-francophones_/volumes/index.tsx"
    },
    "/research_/publications_/dialogue-francophones_/about/": {
      "filePath": "research_/publications_/dialogue-francophones_/about/index.tsx"
    },
    "/research_/publications_/dialogue-francophones_/committees/": {
      "filePath": "research_/publications_/dialogue-francophones_/committees/index.tsx"
    },
    "/research_/publications_/dialogue-francophones_/editorial-policy/": {
      "filePath": "research_/publications_/dialogue-francophones_/editorial-policy/index.tsx"
    },
    "/research_/publications_/dialogue-francophones_/indexing/": {
      "filePath": "research_/publications_/dialogue-francophones_/indexing/index.tsx"
    },
    "/research_/publications_/dialogue-francophones_/volumes/": {
      "filePath": "research_/publications_/dialogue-francophones_/volumes/index.tsx"
    },
    "/research_/publications_/agapes-francophones_/calls_/future/": {
      "filePath": "research_/publications_/agapes-francophones_/calls_/future/index.tsx"
    },
    "/research_/publications_/agapes-francophones_/calls_/past/": {
      "filePath": "research_/publications_/agapes-francophones_/calls_/past/index.tsx"
    },
    "/research_/publications_/dialogue-francophones_/calls_/future/": {
      "filePath": "research_/publications_/dialogue-francophones_/calls_/future/index.tsx"
    },
    "/research_/publications_/dialogue-francophones_/calls_/past/": {
      "filePath": "research_/publications_/dialogue-francophones_/calls_/past/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
